import 'package:flutter/material.dart';

//const kBackgroundColor = Color(0xFFF8F8F8);
//const kActiveIconColor = Color(0xFFE68342);
//const kTextColor = Color(0xFF222B45);
//const kBlueLightColor = Color(0xFFC7B8F5);
//const kBlueColor = Color(0xFF817DC0);
const kShadowColor = Color(0xFFE6E6E6);
const turuncuDefault = Color.fromRGBO(250, 151, 93, 1);
const pictureBgColor = Color.fromRGBO(48, 45, 44, 1);
const defaultLink = Color.fromRGBO(21, 141, 204, 1);
const sariDefault = Color.fromRGBO(253, 196, 37, 1);
final golgeDefault = Color(0xFFD3D3D3).withOpacity(.84);
const linkColor = Color(0xFF3BB3BD);
const cupertionDefault = Color.fromARGB(255, 0, 122, 255);

const topViewColor = Color(0xFFF5CEB8);
const widgetBackgroundColor = Color.fromRGBO(240, 240, 240, 1);
const textDisabledColor = Color.fromRGBO(126, 126, 126, 1);
const turkuazRenk = Color.fromRGBO(65, 202, 198, 1);
final kBoxShadowColor = Color(0xFFD3D3D3).withOpacity(.84);
const profilRenk = Color.fromRGBO(158, 146, 134, 1);

const yesilDefault = Color.fromRGBO(116, 184, 22, 1);
const yesil1 = Color.fromRGBO(192, 235, 117, 1);
const yesil2 = Color.fromRGBO(148, 216, 45, 1);
const yesil3 = Color.fromRGBO(130, 201, 30, 1);
const yesil4 = Color.fromRGBO(116, 184, 22, 1);
const yesil5 = Color.fromRGBO(102, 168, 15, 1);
const yesil6 = Color.fromRGBO(92, 148, 13, 1);

const turkuazDefault = Color.fromRGBO(65, 202, 198, 1);
const turkuazWithOpacity = Color.fromRGBO(65, 202, 198, 0.8);
const turkuazWithOpacity2 = Color.fromRGBO(65, 202, 198, 0.6);
const turkuazWithOpacity3 = Color.fromRGBO(65, 202, 198, 0.4);
const turkuazWithOpacity4 = Color.fromRGBO(65, 202, 198, 0.2);

const morDefault = Color.fromRGBO(82, 67, 101, 1);

const MaterialColor turkuazMaterialColor = const MaterialColor(
  0xFF41CAC6,
  const <int, Color>{
    50: Color.fromRGBO(65, 202, 198, .1),
    100: Color.fromRGBO(65, 202, 198, .2),
    200: Color.fromRGBO(65, 202, 198, .3),
    300: Color.fromRGBO(65, 202, 198, .4),
    400: Color.fromRGBO(65, 202, 198, .5),
    500: Color.fromRGBO(65, 202, 198, .6),
    600: Color.fromRGBO(65, 202, 198, .7),
    700: Color.fromRGBO(65, 202, 198, .8),
    800: Color.fromRGBO(65, 202, 198, .9),
    900: Color.fromRGBO(65, 202, 198, 1),
  },
);

const MaterialColor morMaterialColor = const MaterialColor(
  0xFF524365,
  const <int, Color>{
    50: Color.fromRGBO(82, 67, 101, .1),
    100: Color.fromRGBO(82, 67, 101, .2),
    200: Color.fromRGBO(82, 67, 101, .3),
    300: Color.fromRGBO(82, 67, 101, .4),
    400: Color.fromRGBO(82, 67, 101, .5),
    500: Color.fromRGBO(82, 67, 101, .6),
    600: Color.fromRGBO(82, 67, 101, .7),
    700: Color.fromRGBO(82, 67, 101, .8),
    800: Color.fromRGBO(82, 67, 101, .9),
    900: Color.fromRGBO(82, 67, 101, 1),
  },
);

const defaultTurkuazGradient =
    const LinearGradient(begin: Alignment.topCenter, colors: [
  Color.fromRGBO(65, 202, 198, 1),
  Color.fromRGBO(65, 202, 198, 0.8),
  Color.fromRGBO(65, 202, 198, 0.6),
]);

/// Construct a color from a hex code string, of the format #RRGGBB.
Color hexToColor(String code) {
  return new Color(int.parse(code.substring(1, 7), radix: 16) + 0xFF000000);
}

// Bütün kategoriler
List<String> allCategories = [
  "Bilgisayar",
  "Bilgi Teknolojisi",
  "Din Kültürü ve Ahlak Bilgisi",
  "Drama",
  "Fen Bilgisi",
  "Gölge Öğretmen",
  "Görsel Sanatlar",
  "Halk Oyunları",
  "Hayat Bilgisi",
  "İletişim ve Sunum",
  "Matematik",
  "Müzik",
  "Okuma-Yazma",
  "Oyun Abisi/Ablası",
  "Satranç",
  "Sosyal Bilgiler",
  "Tarım",
  "Tarih",
  "Teknoloji ve Tasarım",
  "Tiyatro",
  "Trafik",
  "Türkçe",
  "Vatandaşlık",
  "Geometri",
  "Anatomi",
  "Araştırma Teknikleri",
  "Astronomi",
  "Biyoloji",
  "Coğrafya",
  "Diksiyon ve Hitabet",
  "Dil ve Anlatım",
  "Ekonomi",
  "Felsefe",
  "Fen Bilimleri",
  "Fizik",
  "Fransız Edebiyatı",
  "Girişimcilik",
  "Grafik Tasarım",
  "İngiliz Edebiyatı",
  "İstatistik",
  "İşletme",
  "İtalyan Edebiyatı",
  "Kimya",
  "Mantık",
  "Osmanlı Türkçesi",
  "Proje Hazırlama",
  "Psikoloji",
  "Sanat Tarihi",
  "Sosyoloji",
  "Astroloji",
  "Batı Dilleri ve Edebiyatı",
  "Bilgisayar Müh.",
  "Biyofizik",
  "Biyokimya",
  "Biyomedikal Müh.",
  "CAD",
  "Çeviri",
  "Deprem Müh.",
  "Diş Hekimliği",
  "Ekonometri",
  "Elektrik Müh.",
  "Elektronik Müh.",
  "Endüstri Müh.",
  "Endüstri Ürünleri Tasarımı",
  "Farmakoloji",
  "Film ve Sinema",
  "Finans",
  "Fizik Müh.",
  "Gemi Müh.",
  "Genetik",
  "Gıda Müh.",
  "Güzel Sanatlar",
  "Harita Müh.",
  "Hukuk",
  "İç Mimarlık",
  "İktisat",
  "İnşaat Müh.",
  "İşletme Müh.",
  "Jeodezi Müh.",
  "Jeofizik Müh.",
  "Jeoloji Müh.",
  "Kimya Müh.",
  "Maden Müh.",
  "Makina Müh.",
  "Mekatronik Müh.",
  "Meteoroloji Müh.",
  "Mikrobiyoloji",
  "Mimarlık",
  "Moleküler Biyoloji",
  "Muhasebe",
  "Nükleer Müh.",
  "Optisyenlik",
  "Orman Müh.",
  "Otomotiv Müh.",
  "Patoloji",
  "Petrol ve Doğal Gaz Müh.",
  "Peyzaj",
  "Ses Mühendisliği",
  "Sistem ve Kontrol Müh.",
  "Siyaset",
  "Sosyal Hizmetler",
  "Şehir ve Bölge Planlama",
  "Tarım Müh.",
  "Tekstil Müh.",
  "Telekomunikasyon Müh.",
  "Tıbbi Sistemler Müh.",
  "Tıp",
  "Ticaret",
  "Turizm",
  "Türk Dili ve Edebiyatı",
  "Uçak Müh.",
  "Uluslararası İlişkiler",
  "Uzay Müh.",
  "Üretim Müh.",
  "Yabancı Dil",
  "Yazılım Müh.",
  "Teknik Resim",
  "Türk Edebiyatı",
  "ACT",
  "Adalet Bakanlığı Sınavları",
  "Adli Yargı",
  "Advanced Placement - Bilgisayar Bilimleri",
  "Advanced Placement - Biyoloji",
  "Advanced Placement - Çevre Bilimleri",
  "Advanced Placement - Fizik",
  "Advanced Placement - İngiliz Edebiyatı",
  "Advanced Placement - İstatistik",
  "Advanced Placement - Kimya",
  "Advanced Placement - Makroekonomi",
  "Advanced Placement - Matematik",
  "Advanced Placement - Mikroekonomi",
  "Advanced Placement - Müzik Teorisi",
  "Advanced Placement - Psikoloji",
  "Advanced Placement - Sanat Tarihi",
  "Aile Birleşim Sınavı",
  "ALES",
  "ALÜGS",
  "ALS",
  "ATPL",
  "AYT",
  "BİLET",
  "BULATS",
  "BÜEPT",
  "CAEL",
  "Cambridge English - YLE Starters",
  "Cambridge English - YLE Movers",
  "Cambridge English - YLE Flyers",
  "Cambridge English - Key (KET)",
  "Cambridge English - Preliminary (PET)",
  "Cambridge English - First (FCE)",
  "Cambridge English - Advanced (CAE)",
  "Cambridge English - Proficiency (CPE)",
  "Cambridge English - Business (BEC)",
  "CEH",
  "CFA",
  "CFE",
  "CISA",
  "CISM",
  "CISSP",
  "CMA",
  "CPA",
  "CPL",
  "CRM",
  "DALF",
  "DELF",
  "DGS",
  "DILF",
  "DİB-MBSTS",
  "DLR",
  "DUS",
  "EKPSS",
  "EKYS",
  "ESOL",
  "GMAT",
  "GRE",
  "GYS",
  "IELTS",
  "İcra Müdür Yardımcılığı",
  "International Baccalaureate - Bilgisayar Bilimleri",
  "International Baccalaureate - Biyoloji",
  "International Baccalaureate - Dans",
  "International Baccalaureate - Drama",
  "International Baccalaureate - Edebiyat",
  "International Baccalaureate - Ekonomi",
  "International Baccalaureate - Felsefe",
  "International Baccalaureate - Filim",
  "International Baccalaureate - Fizik",
  "International Baccalaureate - Görsel Sanatlar",
  "International Baccalaureate - İşletme",
  "International Baccalaureate - Kimya",
  "International Baccalaureate - Matematik",
  "International Baccalaureate - Müzik",
  "International Baccalaureate - Psikoloji",
  "International Baccalaureate - Tarih",
  "International Baccalaureate - Teknoloji",
  "İç Denetçi",
  "İSG",
  "JANA",
  "Kaymakamlık",
  "KDK Uzman Yardımcılığı",
  "KGK Bağımsız Denetçilik",
  "KİT İç Denetçi",
  "KPSS",
  "LGS",
  "LSAT",
  "MCAT",
  "MHUY",
  "MSÜ",
  "Mühendislik Tamamlama",
  "OET",
  "PMP",
  "PMYO",
  "PPL",
  "PTE Academic",
  "PTE General",
  "PTE Young Learners",
  "PYBS",
  "SAT",
  "Sayıştay Eleme",
  "Sayıştay Yazılı",
  "SMMM",
  "SPK",
  "STEP Eiken",
  "STS Diş Hekimliği",
  "STS Eczacılık",
  "STS Tıp Doktorluğu",
  "TEPS",
  "TIPDİL",
  "TMGD",
  "TODAİE",
  "TOEIC",
  "TOEFL",
  "TORFL",
  "TRACE",
  "Trinity College - GESE",
  "Trinity College - ISE",
  "Trinity College - SEW",
  "TUS",
  "TYT",
  "ÜDS",
  "ÜGYS",
  "VDK Müfettiş Yardımcılığı",
  "YDS",
  "YDUS",
  "Yetenek Sınavları - Endüstri Ürünleri Tasarımı",
  "Yetenek Sınavları - Fotoğraf",
  "Yetenek Sınavları - Grafik Tasarım",
  "Yetenek Sınavları - Heykel",
  "Yetenek Sınavları - İç Mimarlık",
  "Yetenek Sınavları - Müzik",
  "Yetenek Sınavları - Resim",
  "Yetenek Sınavları - Sahne Dekorları ve Kostümü",
  "Yetenek Sınavları - Seramik ve Cam Tasarımı",
  "Yetenek Sınavları - Tekstil ve Moda Tasarımı",
  "Yetenek Sınavları - Tiyatro",
  "YKS",
  "YLSY",
  "YMM",
  "YÖKDİL",
  "YÖS",
  "YSK",
  "Afrika Dili",
  "Almanca",
  "Arapça",
  "Arnavutça",
  "Azerice",
  "Baskça",
  "Belarusça",
  "Bengalce",
  "Biharca",
  "Boşnakça",
  "Bretonca",
  "Bulgarca",
  "Çekoslavakça",
  "Çince",
  "Danca",
  "Endonezya Dili",
  "Eritre Dili",
  "Ermenice",
  "Esperantoca",
  "Estonyaca",
  "Farsça",
  "Filipince",
  "Fince",
  "Flemenkçe",
  "Fransızca",
  "Galce",
  "Galiçyaca",
  "Guarani Dili",
  "Gücerat Dili",
  "Gürcüce",
  "Habeşçe",
  "Hintçe",
  "Hırvatça",
  "Hollandaca",
  "İbranice",
  "İngilizce",
  "İnka Dili",
  "İrlandaca",
  "İspanyolca",
  "İsveçce",
  "İtalyanca",
  "İzlandaca",
  "Japonca",
  "Java Dili",
  "Kamboçyaca",
  "Katalanca",
  "Kazakça",
  "Kırgızca",
  "Klingonca",
  "Korece",
  "Korsika Dili",
  "Kürtçe",
  "Kuzey İskoç Dili",
  "Laosça",
  "Latince",
  "Lehçe",
  "Letonyaca",
  "Lingalaca",
  "Litvanyaca",
  "Macarca",
  "Makedonca",
  "Malayalam",
  "Malezya Dili",
  "Maltaca",
  "Marathi",
  "Moğolca",
  "Moldovyaca",
  "Nepalce",
  "Norveçce",
  "Osmanlıca",
  "Özbekçe",
  "Pencap Dili",
  "Peştuca",
  "Polonyaca",
  "Portekizce",
  "Romanşça",
  "Romence",
  "Rusça",
  "Sesotho Dili",
  "Sırpça",
  "Slovakça",
  "Slovence",
  "Somalice",
  "Sri Lankaca",
  "Sundanizce",
  "Svahili",
  "Tacikce",
  "Tamil",
  "Tatarca",
  "Tay Dili",
  "Telugu",
  "Tongaca",
  "Türkmence",
  "Tvi Dili",
  "Ukraynaca",
  "Urduca",
  "Uygur Dili",
  "Vietnamca",
  "Yidce",
  "Yoruba Dili",
  "Yunanca",
  "Zulu Dili",
  "3D Max",
  "Abaqus",
  "Adobe After Effects",
  "Adobe Dreamweaver",
  "Adobe Flash",
  "Adobe FreeHand",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Premiere",
  "Android",
  "AngularJS",
  "Animasyon",
  "Ansys APDL",
  "Ansys Workbench",
  "ArcGIS",
  "Arduino",
  "ASP",
  "ASP.NET Core",
  "ASP.NET MVC",
  "ASP.NET Web API",
  "ASP.NET Web Forms",
  "AutoCAD",
  "AutoCAD Civil 3D",
  "AutoCAD Plant 3D",
  "Autodesk Advance Steel",
  "Autodesk Fusion 360",
  "Autodesk Inventor",
  "Autodesk Navisworks",
  "Autodesk Revit",
  "Autodesk Robot Structural Analysis",
  "AutoForm",
  "Bilgisayarlı Muhasebe",
  "Bilişim Sistemleri",
  "Blender",
  "C",
  "C#",
  "C++",
  "Catia",
  "Clips",
  "CNC",
  "Cobol",
  "CorelDraw",
  "Derin Öğrenme",
  "DiaLux",
  "Doğal Dil İşleme",
  "Donanım",
  "Etabs",
  "Go",
  "HTML",
  "İnternet",
  "iOS",
  "İşletim Sistemleri",
  "J2EE",
  "J2EE - Hibernate",
  "J2EE - Spring",
  "J2EE - Struts",
  "Java",
  "Javascript",
  "JQuery",
  "JSP",
  "Keynote",
  "KeyShot",
  "Kodlama",
  "LINQ",
  "Linux",
  "LS-Dyna",
  "Lumion",
  "MacOS",
  "Makine Öğrenmesi",
  "Matlab",
  "Marc",
  "Mobil Uygulama Geliştirme",
  "Modelleme",
  "MS .NET",
  "MS Access",
  "MS Excel",
  "MS FoxPro",
  "MS Outlook",
  "MS PowerPoint",
  "MS Project",
  "MS Visio",
  "MS Visual Basic",
  "MS Windows",
  "MS Word",
  "Multimedya",
  "Müzik Yapımı",
  "MySQL",
  "Netcad",
  "Network",
  "Node.JS",
  "NX Unigraphics",
  "Oracle",
  "Pascal",
  "Perl",
  "PhoneGap",
  "Photoshop",
  "PHP",
  "PHP - Symfony",
  "Prezi",
  "Programlama",
  "Prolog",
  "Python",
  "R",
  "React Native",
  "Rhinoceros 3D",
  "Robotik",
  "Ruby On Rails",
  "SAS",
  "SAP",
  "Sap2000",
  "SEO",
  "Simulia",
  "Simulink",
  "SketchUp",
  "SolidCAM",
  "SolidWorks",
  "SPSS",
  "SQL",
  "Sta4CAD",
  "TCP/IP",
  "Tekla Xsteel",
  "Temel Bilgisayar Bilgisi",
  "Unity",
  "Unix",
  "Uygulama Geliştirme",
  "Veritabanları",
  "Web Programlama",
  "Web Tasarımı",
  "Xamarin",
  "XCode",
  "Yapay Sinir Ağları",
  "Yapay Zeka",
  "Yazılım Mühendisliği",
  "Akordiyon",
  "Armoni",
  "Bağlama",
  "Bariton",
  "Bas",
  "Bateri",
  "Bongo",
  "Borazan",
  "Buzuki",
  "Cümbüş",
  "Çello",
  "Darbuka",
  "Davul",
  "Flüt",
  "Gitar",
  "Harmonika",
  "Harp",
  "Kabak Kemane",
  "Kanun",
  "Kaval",
  "Keman",
  "Kemençe",
  "Klarnet",
  "Klavye",
  "Kompozisyon",
  "Kontrabas",
  "Lavta",
  "Mandolin",
  "Marakas",
  "Melodika",
  "Mızıka",
  "Mızrap",
  "Müzik Prodüksiyon",
  "Müzik Tarihi",
  "Müzik Teknolojileri",
  "Müzik Teorisi",
  "Nefesli Çalgılar",
  "Ney",
  "Oboe",
  "Org",
  "Piano",
  "Saksofon",
  "Saz",
  "Ses Üretimi",
  "Solfej",
  "Şan",
  "Şarkı Aranje",
  "Şarkı Besteleme",
  "Şarkı Kayıt",
  "Tambur",
  "Tef",
  "Telli Çalgılar",
  "Trombon",
  "Trompet",
  "Tuba",
  "Tulum",
  "Tumba",
  "Tuşlu Çalgılar",
  "Türk Müziği",
  "Ud",
  "Ukulele",
  "Viyola",
  "Vurmalı Çalgılar",
  "Yan Flüt",
  "Zil",
  "Zurna",
  "Atıcılık",
  "Badminton",
  "Basketbol",
  "Bilek Güreşi",
  "Binicilik",
  "Bisiklet",
  "Boks",
  "Dalış",
  "Futbol",
  "Golf",
  "Güreş",
  "Jimnastik",
  "Kayak",
  "Masa Tenisi",
  "Motor Sporları",
  "Okçuluk",
  "Oryantiring",
  "Paraşüt",
  "Paten",
  "Pilates",
  "Rüzgar Sörfü",
  "Skuba",
  "Sörf",
  "Tenis",
  "Uzak Doğu Sporları",
  "Voleybol",
  "Vücut geliştirme",
  "Yamaç Paraşütü",
  "Yelkencilik",
  "Yoga",
  "Yüzme",
  "Zumba",
  "Cam İşleme",
  "Çizim",
  "Dikiş Nakış Terzilik",
  "Dövme Yapımı",
  "Fotoğrafcılık",
  "Heykel",
  "İç Tasarım",
  "İllüstrasyon",
  "İllüzyon",
  "Kaligrafi",
  "Kara Kalem",
  "Karikatür",
  "Opera",
  "Oyun Yazımı",
  "Örgü",
  "Öykü Yazımı",
  "Resim",
  "Roman Yazımı",
  "Seramik",
  "Sinema",
  "Takı Tasarımı",
  "Yaratıcı Yazarlık",
  "Şarkı Ka",
  "Bale",
  "Bchata",
  "Break Dans",
  "Bolero",
  "Cha Cha",
  "Foxtrot",
  "Jive",
  "Koreografi",
  "Mambo",
  "Merenge",
  "Modern Dans",
  "Oryantal",
  "Paso Doble",
  "Quickstep",
  "Rumba",
  "Salsa",
  "Samba",
  "Tango",
  "Waltz",
  "Borsa",
  "Denetim - Bilgi Teknolojileri",
  "Denetim - Finansal Denetim",
  "Denetim - İç Denetim",
  "Denetim - Vergi Denetimi",
  "Editörlük",
  "Güzel Konuşma",
  "Hafıza Geliştirme",
  "Halkla İlişkiler",
  "Hızlı Okuma",
  "İletişim",
  "İş İdaresi",
  "İş Kurma",
  "İş Planlama",
  "İş Sürekliliği Yönetimi",
  "Kariyer Planlama",
  "Mental Aritmetik",
  "NLP",
  "Numeroloji",
  "Pazarlama",
  "Prezentasyon",
  "Proje Yönetimi",
  "Reklamcılık",
  "Rezüme Hazırlama",
  "Risk Yönetimi",
  "Satış",
  "Stenografi",
  "Stratejik Planlama",
  "Vergi",
  "Yazmayı Öğrenme",
  "Yöneticilik",
  "Zaman Yönetimi",
  "Otomobil",
  "Otobüs",
  "Motosiklet",
  "Kamyon",
  "İş Makinaları",
  "Dil ve Konuşma Bozuklukları",
  "Down Sendromu",
  "Fiziksel Engelliler",
  "Görme Engelliler",
  "İşitme Engelliler",
  "Okuma Yazma Güçlüğü",
  "Ortopedik Engelliler",
  "Otizim Spektrum Bozukluğu",
  "Özgül Öğrenme Problemi",
  "Uyum Güçlügü Olan Çocuklar",
  "Üstün Yetenekli Çocuklar",
  "Zihinsel Engelliler",
  "Amigurumi",
  "Akıl Oyunları",
  "Bilardo",
  "Bowling",
  "Briç",
  "Dama",
  "Go Oyunu",
  "Kart Oyunları",
  "Okey",
  "Origami",
  "Poker",
  "Tavla"
];
