import 'package:flutter/material.dart';

//const kBackgroundColor = Color(0xFFF8F8F8);
//const kActiveIconColor = Color(0xFFE68342);
//const kTextColor = Color(0xFF222B45);
//const kBlueLightColor = Color(0xFFC7B8F5);
//const kBlueColor = Color(0xFF817DC0);
const kShadowColor = Color(0xFFE6E6E6);
const turuncuDefault = Color.fromRGBO(250, 151, 93, 1);
const pictureBgColor = Color.fromRGBO(48, 45, 44, 1);
const dangerDefault = Color.fromRGBO(217, 83, 79, 1);
const successDefault = Color.fromRGBO(92, 184, 92, 1);

const defaultLink = Color.fromRGBO(21, 141, 204, 1);
const sariDefault = Color.fromRGBO(253, 196, 37, 1);
final golgeDefault = Color(0xFFD3D3D3).withOpacity(.84);
const linkColor = Color(0xFF3BB3BD);
const cupertionDefault = Color.fromARGB(255, 0, 122, 255);

const topViewColor = Color(0xFFF5CEB8);
const widgetBackgroundColor = Color.fromRGBO(240, 240, 240, 1);
const textDisabledColor = Color.fromRGBO(126, 126, 126, 1);
const turkuazRenk = Color.fromRGBO(65, 202, 198, 1);
final kBoxShadowColor = Color(0xFFD3D3D3).withOpacity(.84);
const profilRenk = Color.fromRGBO(158, 146, 134, 1);

const yesilDefault = Color.fromRGBO(116, 184, 22, 1);
const yesil1 = Color.fromRGBO(192, 235, 117, 1);
const yesil2 = Color.fromRGBO(148, 216, 45, 1);
const yesil3 = Color.fromRGBO(130, 201, 30, 1);
const yesil4 = Color.fromRGBO(116, 184, 22, 1);
const yesil5 = Color.fromRGBO(102, 168, 15, 1);
const yesil6 = Color.fromRGBO(92, 148, 13, 1);

const turkuazDefault = Color.fromRGBO(65, 202, 198, 1);
const turkuazWithOpacity = Color.fromRGBO(65, 202, 198, 0.8);
const turkuazWithOpacity2 = Color.fromRGBO(65, 202, 198, 0.6);
const turkuazWithOpacity3 = Color.fromRGBO(65, 202, 198, 0.4);
const turkuazWithOpacity4 = Color.fromRGBO(65, 202, 198, 0.2);

const morDefault = Color.fromRGBO(82, 67, 101, 1);

const MaterialColor turkuazMaterialColor = const MaterialColor(
  0xFF41CAC6,
  const <int, Color>{
    50: Color.fromRGBO(65, 202, 198, .1),
    100: Color.fromRGBO(65, 202, 198, .2),
    200: Color.fromRGBO(65, 202, 198, .3),
    300: Color.fromRGBO(65, 202, 198, .4),
    400: Color.fromRGBO(65, 202, 198, .5),
    500: Color.fromRGBO(65, 202, 198, .6),
    600: Color.fromRGBO(65, 202, 198, .7),
    700: Color.fromRGBO(65, 202, 198, .8),
    800: Color.fromRGBO(65, 202, 198, .9),
    900: Color.fromRGBO(65, 202, 198, 1),
  },
);

const MaterialColor morMaterialColor = const MaterialColor(
  0xFF524365,
  const <int, Color>{
    50: Color.fromRGBO(82, 67, 101, .1),
    100: Color.fromRGBO(82, 67, 101, .2),
    200: Color.fromRGBO(82, 67, 101, .3),
    300: Color.fromRGBO(82, 67, 101, .4),
    400: Color.fromRGBO(82, 67, 101, .5),
    500: Color.fromRGBO(82, 67, 101, .6),
    600: Color.fromRGBO(82, 67, 101, .7),
    700: Color.fromRGBO(82, 67, 101, .8),
    800: Color.fromRGBO(82, 67, 101, .9),
    900: Color.fromRGBO(82, 67, 101, 1),
  },
);

const defaultTurkuazGradient = const LinearGradient(begin: Alignment.topCenter, colors: [
  Color.fromRGBO(65, 202, 198, 1),
  Color.fromRGBO(65, 202, 198, 0.8),
  Color.fromRGBO(65, 202, 198, 0.6),
]);

/// Construct a color from a hex code string, of the format #RRGGBB.
Color hexToColor(String code) {
  return new Color(int.parse(code.substring(1, 7), radix: 16) + 0xFF000000);
}

// Bütün kategoriler
List<String> allCategories = [
  "3D Max",
  "ACT",
  "ALES",
  "ALS",
  "ALÜGS",
  "ASP",
  "ASP.NET Core",
  "ASP.NET MVC",
  "ASP.NET Web API",
  "ASP.NET Web Forms",
  "ATPL",
  "AYT",
  "Abaqus",
  "Adalet Bakanlığı Sınavları",
  "Adli Yargı",
  "Adobe After Effects",
  "Adobe Dreamweaver",
  "Adobe Flash",
  "Adobe FreeHand",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Premiere",
  "Advanced Placement - Bilgisayar Bilimleri",
  "Advanced Placement - Biyoloji",
  "Advanced Placement - Fizik",
  "Advanced Placement - Kimya",
  "Advanced Placement - Makroekonomi",
  "Advanced Placement - Matematik",
  "Advanced Placement - Mikroekonomi",
  "Advanced Placement - Müzik Teorisi",
  "Advanced Placement - Psikoloji",
  "Advanced Placement - Sanat Tarihi",
  "Advanced Placement - Çevre Bilimleri",
  "Advanced Placement - İngiliz Edebiyatı",
  "Advanced Placement - İstatistik",
  "Afrika Dili",
  "Aile Birleşim Sınavı",
  "Akordiyon",
  "Akıl Oyunları",
  "Almanca",
  "Amigurumi",
  "Anatomi",
  "Android",
  "AngularJS",
  "Animasyon",
  "Ansys APDL",
  "Ansys Workbench",
  "Arapça",
  "Araştırma Teknikleri",
  "ArcGIS",
  "Arduino",
  "Armoni",
  "Arnavutça",
  "Astroloji",
  "Astronomi",
  "Atıcılık",
  "AutoCAD",
  "AutoCAD Civil 3D",
  "AutoCAD Plant 3D",
  "AutoForm",
  "Autodesk Advance Steel",
  "Autodesk Fusion 360",
  "Autodesk Inventor",
  "Autodesk Navisworks",
  "Autodesk Revit",
  "Autodesk Robot Structural Analysis",
  "Azerice",
  "BULATS",
  "Badminton",
  "Bale",
  "Bariton",
  "Bas",
  "Basketbol",
  "Baskça",
  "Bateri",
  "Batı Dilleri ve Edebiyatı",
  "Bağlama",
  "Bchata",
  "Belarusça",
  "Bengalce",
  "Biharca",
  "Bilardo",
  "Bilek Güreşi",
  "Bilgi Teknolojisi",
  "Bilgisayar",
  "Bilgisayar Müh.",
  "Bilgisayarlı Muhasebe",
  "Bilişim Sistemleri",
  "Binicilik",
  "Bisiklet",
  "Biyofizik",
  "Biyokimya",
  "Biyoloji",
  "Biyomedikal Müh.",
  "Blender",
  "Boks",
  "Bolero",
  "Bongo",
  "Borazan",
  "Borsa",
  "Bowling",
  "Boşnakça",
  "Break Dans",
  "Bretonca",
  "Briç",
  "Bulgarca",
  "Buzuki",
  "BÜEPT",
  "BİLET",
  "C",
  "C#",
  "C++",
  "CAD",
  "CAEL",
  "CEH",
  "CFA",
  "CFE",
  "CISA",
  "CISM",
  "CISSP",
  "CMA",
  "CNC",
  "CPA",
  "CPL",
  "CRM",
  "Cam İşleme",
  "Cambridge English - Advanced (CAE)",
  "Cambridge English - Business (BEC)",
  "Cambridge English - First (FCE)",
  "Cambridge English - Key (KET)",
  "Cambridge English - Preliminary (PET)",
  "Cambridge English - Proficiency (CPE)",
  "Cambridge English - YLE Flyers",
  "Cambridge English - YLE Movers",
  "Cambridge English - YLE Starters",
  "Catia",
  "Cha Cha",
  "Clips",
  "Cobol",
  "CorelDraw",
  "Coğrafya",
  "Cümbüş",
  "DALF",
  "DELF",
  "DGS",
  "DILF",
  "DLR",
  "DUS",
  "Dalış",
  "Dama",
  "Danca",
  "Darbuka",
  "Davul",
  "Denetim - Bilgi Teknolojileri",
  "Denetim - Finansal Denetim",
  "Denetim - Vergi Denetimi",
  "Denetim - İç Denetim",
  "Deprem Müh.",
  "Derin Öğrenme",
  "DiaLux",
  "Dikiş Nakış Terzilik",
  "Diksiyon ve Hitabet",
  "Dil ve Anlatım",
  "Dil ve Konuşma Bozuklukları",
  "Din Kültürü ve Ahlak Bilgisi",
  "Diş Hekimliği",
  "Donanım",
  "Down Sendromu",
  "Doğal Dil İşleme",
  "Drama",
  "Dövme Yapımı",
  "DİB-MBSTS",
  "EKPSS",
  "EKYS",
  "ESOL",
  "Editörlük",
  "Ekonometri",
  "Ekonomi",
  "Elektrik Müh.",
  "Elektronik Müh.",
  "Endonezya Dili",
  "Endüstri Müh.",
  "Endüstri Ürünleri Tasarımı",
  "Eritre Dili",
  "Ermenice",
  "Esperantoca",
  "Estonyaca",
  "Etabs",
  "Farmakoloji",
  "Farsça",
  "Felsefe",
  "Fen Bilgisi",
  "Fen Bilimleri",
  "Filipince",
  "Film ve Sinema",
  "Finans",
  "Fince",
  "Fizik",
  "Fizik Müh.",
  "Fiziksel Engelliler",
  "Flemenkçe",
  "Flüt",
  "Fotoğrafcılık",
  "Foxtrot",
  "Fransız Edebiyatı",
  "Fransızca",
  "Futbol",
  "GMAT",
  "GRE",
  "GYS",
  "Galce",
  "Galiçyaca",
  "Gemi Müh.",
  "Genetik",
  "Geometri",
  "Girişimcilik",
  "Gitar",
  "Go",
  "Go Oyunu",
  "Golf",
  "Grafik Tasarım",
  "Guarani Dili",
  "Gölge Öğretmen",
  "Görme Engelliler",
  "Görsel Sanatlar",
  "Gücerat Dili",
  "Gürcüce",
  "Güreş",
  "Güzel Konuşma",
  "Güzel Sanatlar",
  "Gıda Müh.",
  "HTML",
  "Habeşçe",
  "Hafıza Geliştirme",
  "Halk Oyunları",
  "Halkla İlişkiler",
  "Harita Müh.",
  "Harmonika",
  "Harp",
  "Hayat Bilgisi",
  "Heykel",
  "Hintçe",
  "Hollandaca",
  "Hukuk",
  "Hırvatça",
  "Hızlı Okuma",
  "IELTS",
  "International Baccalaureate - Bilgisayar Bilimleri",
  "International Baccalaureate - Biyoloji",
  "International Baccalaureate - Dans",
  "International Baccalaureate - Drama",
  "International Baccalaureate - Edebiyat",
  "International Baccalaureate - Ekonomi",
  "International Baccalaureate - Felsefe",
  "International Baccalaureate - Filim",
  "International Baccalaureate - Fizik",
  "International Baccalaureate - Görsel Sanatlar",
  "International Baccalaureate - Kimya",
  "International Baccalaureate - Matematik",
  "International Baccalaureate - Müzik",
  "International Baccalaureate - Psikoloji",
  "International Baccalaureate - Tarih",
  "International Baccalaureate - Teknoloji",
  "International Baccalaureate - İşletme",
  "J2EE",
  "J2EE - Hibernate",
  "J2EE - Spring",
  "J2EE - Struts",
  "JANA",
  "JQuery",
  "JSP",
  "Japonca",
  "Java",
  "Java Dili",
  "Javascript",
  "Jeodezi Müh.",
  "Jeofizik Müh.",
  "Jeoloji Müh.",
  "Jimnastik",
  "Jive",
  "KDK Uzman Yardımcılığı",
  "KGK Bağımsız Denetçilik",
  "KPSS",
  "Kabak Kemane",
  "Kaligrafi",
  "Kamboçyaca",
  "Kamyon",
  "Kanun",
  "Kara Kalem",
  "Karikatür",
  "Kariyer Planlama",
  "Kart Oyunları",
  "Katalanca",
  "Kaval",
  "Kayak",
  "Kaymakamlık",
  "Kazakça",
  "Keman",
  "Kemençe",
  "KeyShot",
  "Keynote",
  "Kimya",
  "Kimya Müh.",
  "Klarnet",
  "Klavye",
  "Klingonca",
  "Kodlama",
  "Kompozisyon",
  "Kontrabas",
  "Korece",
  "Koreografi",
  "Korsika Dili",
  "Kuzey İskoç Dili",
  "Kürtçe",
  "KİT İç Denetçi",
  "Kırgızca",
  "LGS",
  "LINQ",
  "LS-Dyna",
  "LSAT",
  "Laosça",
  "Latince",
  "Lavta",
  "Lehçe",
  "Letonyaca",
  "Lingalaca",
  "Linux",
  "Litvanyaca",
  "Lumion",
  "MCAT",
  "MHUY",
  "MS .NET",
  "MS Access",
  "MS Excel",
  "MS FoxPro",
  "MS Outlook",
  "MS PowerPoint",
  "MS Project",
  "MS Visio",
  "MS Visual Basic",
  "MS Windows",
  "MS Word",
  "MSÜ",
  "MacOS",
  "Macarca",
  "Maden Müh.",
  "Makedonca",
  "Makina Müh.",
  "Makine Öğrenmesi",
  "Malayalam",
  "Malezya Dili",
  "Maltaca",
  "Mambo",
  "Mandolin",
  "Mantık",
  "Marakas",
  "Marathi",
  "Marc",
  "Masa Tenisi",
  "Matematik",
  "Matlab",
  "Mekatronik Müh.",
  "Melodika",
  "Mental Aritmetik",
  "Merenge",
  "Meteoroloji Müh.",
  "Mikrobiyoloji",
  "Mimarlık",
  "Mobil Uygulama Geliştirme",
  "Modelleme",
  "Modern Dans",
  "Moldovyaca",
  "Moleküler Biyoloji",
  "Motor Sporları",
  "Motosiklet",
  "Moğolca",
  "Muhasebe",
  "Multimedya",
  "MySQL",
  "Mühendislik Tamamlama",
  "Müzik",
  "Müzik Prodüksiyon",
  "Müzik Tarihi",
  "Müzik Teknolojileri",
  "Müzik Teorisi",
  "Müzik Yapımı",
  "Mızrap",
  "Mızıka",
  "NLP",
  "NX Unigraphics",
  "Nefesli Çalgılar",
  "Nepalce",
  "Netcad",
  "Network",
  "Ney",
  "Node.JS",
  "Norveçce",
  "Numeroloji",
  "Nükleer Müh.",
  "OET",
  "Oboe",
  "Okey",
  "Okuma Yazma Güçlüğü",
  "Okuma-Yazma",
  "Okçuluk",
  "Opera",
  "Optisyenlik",
  "Oracle",
  "Org",
  "Origami",
  "Orman Müh.",
  "Ortopedik Engelliler",
  "Oryantal",
  "Oryantiring",
  "Osmanlı Türkçesi",
  "Osmanlıca",
  "Otizim Spektrum Bozukluğu",
  "Otobüs",
  "Otomobil",
  "Otomotiv Müh.",
  "Oyun Abisi/Ablası",
  "Oyun Yazımı",
  "PHP",
  "PHP - Symfony",
  "PMP",
  "PMYO",
  "PPL",
  "PTE Academic",
  "PTE General",
  "PTE Young Learners",
  "PYBS",
  "Paraşüt",
  "Pascal",
  "Paso Doble",
  "Paten",
  "Patoloji",
  "Pazarlama",
  "Pencap Dili",
  "Perl",
  "Petrol ve Doğal Gaz Müh.",
  "Peyzaj",
  "Peştuca",
  "PhoneGap",
  "Photoshop",
  "Piano",
  "Pilates",
  "Poker",
  "Polonyaca",
  "Portekizce",
  "Prezentasyon",
  "Prezi",
  "Programlama",
  "Proje Hazırlama",
  "Proje Yönetimi",
  "Prolog",
  "Psikoloji",
  "Python",
  "Quickstep",
  "R",
  "React Native",
  "Reklamcılık",
  "Resim",
  "Rezüme Hazırlama",
  "Rhinoceros 3D",
  "Risk Yönetimi",
  "Robotik",
  "Roman Yazımı",
  "Romanşça",
  "Romence",
  "Ruby On Rails",
  "Rumba",
  "Rusça",
  "Rüzgar Sörfü",
  "SAP",
  "SAS",
  "SAT",
  "SEO",
  "SMMM",
  "SPK",
  "SPSS",
  "SQL",
  "STEP Eiken",
  "STS Diş Hekimliği",
  "STS Eczacılık",
  "STS Tıp Doktorluğu",
  "Saksofon",
  "Salsa",
  "Samba",
  "Sanat Tarihi",
  "Sap2000",
  "Satranç",
  "Satış",
  "Sayıştay Eleme",
  "Sayıştay Yazılı",
  "Saz",
  "Seramik",
  "Ses Mühendisliği",
  "Ses Üretimi",
  "Sesotho Dili",
  "Simulia",
  "Simulink",
  "Sinema",
  "Sistem ve Kontrol Müh.",
  "Siyaset",
  "SketchUp",
  "Skuba",
  "Slovakça",
  "Slovence",
  "Solfej",
  "SolidCAM",
  "SolidWorks",
  "Somalice",
  "Sosyal Bilgiler",
  "Sosyal Hizmetler",
  "Sosyoloji",
  "Sri Lankaca",
  "Sta4CAD",
  "Stenografi",
  "Stratejik Planlama",
  "Sundanizce",
  "Svahili",
  "Sörf",
  "Sırpça",
  "TCP/IP",
  "TEPS",
  "TIPDİL",
  "TMGD",
  "TODAİE",
  "TOEFL",
  "TOEIC",
  "TORFL",
  "TRACE",
  "TUS",
  "TYT",
  "Tacikce",
  "Takı Tasarımı",
  "Tambur",
  "Tamil",
  "Tango",
  "Tarih",
  "Tarım",
  "Tarım Müh.",
  "Tatarca",
  "Tavla",
  "Tay Dili",
  "Tef",
  "Tekla Xsteel",
  "Teknik Resim",
  "Teknoloji ve Tasarım",
  "Tekstil Müh.",
  "Telekomunikasyon Müh.",
  "Telli Çalgılar",
  "Telugu",
  "Temel Bilgisayar Bilgisi",
  "Tenis",
  "Ticaret",
  "Tiyatro",
  "Tongaca",
  "Trafik",
  "Trinity College - GESE",
  "Trinity College - ISE",
  "Trinity College - SEW",
  "Trombon",
  "Trompet",
  "Tuba",
  "Tulum",
  "Tumba",
  "Turizm",
  "Tuşlu Çalgılar",
  "Tvi Dili",
  "Türk Dili ve Edebiyatı",
  "Türk Edebiyatı",
  "Türk Müziği",
  "Türkmence",
  "Türkçe",
  "Tıbbi Sistemler Müh.",
  "Tıp",
  "Ud",
  "Ukraynaca",
  "Ukulele",
  "Uluslararası İlişkiler",
  "Unity",
  "Unix",
  "Urduca",
  "Uygulama Geliştirme",
  "Uygur Dili",
  "Uyum Güçlügü Olan Çocuklar",
  "Uzak Doğu Sporları",
  "Uzay Müh.",
  "Uçak Müh.",
  "VDK Müfettiş Yardımcılığı",
  "Vatandaşlık",
  "Vergi",
  "Veritabanları",
  "Vietnamca",
  "Viyola",
  "Voleybol",
  "Vurmalı Çalgılar",
  "Vücut geliştirme",
  "Waltz",
  "Web Programlama",
  "Web Tasarımı",
  "XCode",
  "Xamarin",
  "YDS",
  "YDUS",
  "YKS",
  "YLSY",
  "YMM",
  "YSK",
  "Yabancı Dil",
  "Yamaç Paraşütü",
  "Yan Flüt",
  "Yapay Sinir Ağları",
  "Yapay Zeka",
  "Yaratıcı Yazarlık",
  "Yazmayı Öğrenme",
  "Yazılım Müh.",
  "Yazılım Mühendisliği",
  "Yelkencilik",
  "Yetenek Sınavları - Endüstri Ürünleri Tasarımı",
  "Yetenek Sınavları - Fotoğraf",
  "Yetenek Sınavları - Grafik Tasarım",
  "Yetenek Sınavları - Heykel",
  "Yetenek Sınavları - Müzik",
  "Yetenek Sınavları - Resim",
  "Yetenek Sınavları - Sahne Dekorları ve Kostümü",
  "Yetenek Sınavları - Seramik ve Cam Tasarımı",
  "Yetenek Sınavları - Tekstil ve Moda Tasarımı",
  "Yetenek Sınavları - Tiyatro",
  "Yetenek Sınavları - İç Mimarlık",
  "Yidce",
  "Yoga",
  "Yoruba Dili",
  "Yunanca",
  "YÖKDİL",
  "YÖS",
  "Yöneticilik",
  "Yüzme",
  "Zaman Yönetimi",
  "Zihinsel Engelliler",
  "Zil",
  "Zulu Dili",
  "Zumba",
  "Zurna",
  "iOS",
  "Çekoslavakça",
  "Çello",
  "Çeviri",
  "Çince",
  "Çizim",
  "Örgü",
  "Öykü Yazımı",
  "Özbekçe",
  "Özgül Öğrenme Problemi",
  "ÜDS",
  "ÜGYS",
  "Üretim Müh.",
  "Üstün Yetenekli Çocuklar",
  "İSG",
  "İbranice",
  "İcra Müdür Yardımcılığı",
  "İktisat",
  "İletişim",
  "İletişim ve Sunum",
  "İllüstrasyon",
  "İllüzyon",
  "İngiliz Edebiyatı",
  "İngilizce",
  "İnka Dili",
  "İnternet",
  "İnşaat Müh.",
  "İrlandaca",
  "İspanyolca",
  "İstatistik",
  "İsveçce",
  "İtalyan Edebiyatı",
  "İtalyanca",
  "İzlandaca",
  "İç Denetçi",
  "İç Mimarlık",
  "İç Tasarım",
  "İş Kurma",
  "İş Makinaları",
  "İş Planlama",
  "İş Sürekliliği Yönetimi",
  "İş İdaresi",
  "İşitme Engelliler",
  "İşletim Sistemleri",
  "İşletme",
  "İşletme Müh.",
  "Şan",
  "Şarkı Aranje",
  "Şarkı Besteleme",
  "Şarkı Ka",
  "Şarkı Kayıt",
  "Şehir ve Bölge Planlama"
];

List allStatesOfTurkey = [
  {"kodu": "0", "aciklama": "Seçim Yapınız"},
  {"kodu": "1", "aciklama": "Adana"},
  {"kodu": "2", "aciklama": "Adıyaman"},
  {"kodu": "3", "aciklama": "Afyonkarahisar"},
  {"kodu": "4", "aciklama": "Ağrı"},
  {"kodu": "5", "aciklama": "Amasya"},
  {"kodu": "6", "aciklama": "Ankara"},
  {"kodu": "7", "aciklama": "Antalya"},
  {"kodu": "8", "aciklama": "Artvin"},
  {"kodu": "9", "aciklama": "Aydın"},
  {"kodu": "10", "aciklama": "Balıkesir"},
  {"kodu": "11", "aciklama": "Bilecik"},
  {"kodu": "12", "aciklama": "Bingöl"},
  {"kodu": "13", "aciklama": "Bitlis"},
  {"kodu": "14", "aciklama": "Bolu"},
  {"kodu": "15", "aciklama": "Burdur"},
  {"kodu": "16", "aciklama": "Bursa"},
  {"kodu": "17", "aciklama": "Çanakkale"},
  {"kodu": "18", "aciklama": "Çankırı"},
  {"kodu": "19", "aciklama": "Çorum"},
  {"kodu": "20", "aciklama": "Denizli"},
  {"kodu": "21", "aciklama": "Diyarbakır"},
  {"kodu": "22", "aciklama": "Edirne"},
  {"kodu": "23", "aciklama": "Elazığ"},
  {"kodu": "24", "aciklama": "Erzincan"},
  {"kodu": "25", "aciklama": "Erzurum"},
  {"kodu": "26", "aciklama": "Eskişehir"},
  {"kodu": "27", "aciklama": "Gaziantep"},
  {"kodu": "28", "aciklama": "Giresun"},
  {"kodu": "29", "aciklama": "Gümüşhane"},
  {"kodu": "30", "aciklama": "Hakkari"},
  {"kodu": "31", "aciklama": "Hatay"},
  {"kodu": "32", "aciklama": "Isparta"},
  {"kodu": "33", "aciklama": "Mersin"},
  {"kodu": "34", "aciklama": "İstanbul"},
  {"kodu": "35", "aciklama": "İzmir"},
  {"kodu": "36", "aciklama": "Kars"},
  {"kodu": "37", "aciklama": "Kastamonu"},
  {"kodu": "38", "aciklama": "Kayseri"},
  {"kodu": "39", "aciklama": "Kırklareli"},
  {"kodu": "40", "aciklama": "Kırşehir"},
  {"kodu": "41", "aciklama": "Kocaeli"},
  {"kodu": "42", "aciklama": "Konya"},
  {"kodu": "43", "aciklama": "Kütahya"},
  {"kodu": "44", "aciklama": "Malatya"},
  {"kodu": "45", "aciklama": "Manisa"},
  {"kodu": "46", "aciklama": "Kahramanmaraş"},
  {"kodu": "47", "aciklama": "Mardin"},
  {"kodu": "48", "aciklama": "Muğla"},
  {"kodu": "49", "aciklama": "Muş"},
  {"kodu": "50", "aciklama": "Nevşehir"},
  {"kodu": "51", "aciklama": "Niğde"},
  {"kodu": "52", "aciklama": "Ordu"},
  {"kodu": "53", "aciklama": "Rize"},
  {"kodu": "54", "aciklama": "Sakarya"},
  {"kodu": "55", "aciklama": "Samsun"},
  {"kodu": "56", "aciklama": "Siirt"},
  {"kodu": "57", "aciklama": "Sinop"},
  {"kodu": "58", "aciklama": "Sivas"},
  {"kodu": "59", "aciklama": "Tekirdağ"},
  {"kodu": "60", "aciklama": "Tokat"},
  {"kodu": "61", "aciklama": "Trabzon"},
  {"kodu": "62", "aciklama": "Tunceli"},
  {"kodu": "63", "aciklama": "Şanlıurfa"},
  {"kodu": "64", "aciklama": "Uşak"},
  {"kodu": "65", "aciklama": "Van"},
  {"kodu": "66", "aciklama": "Yozgat"},
  {"kodu": "67", "aciklama": "Zonguldak"},
  {"kodu": "68", "aciklama": "Aksaray"},
  {"kodu": "69", "aciklama": "Bayburt"},
  {"kodu": "70", "aciklama": "Karaman"},
  {"kodu": "71", "aciklama": "Kırıkkale"},
  {"kodu": "72", "aciklama": "Batman"},
  {"kodu": "73", "aciklama": "Şırnak"},
  {"kodu": "74", "aciklama": "Bartın"},
  {"kodu": "75", "aciklama": "Ardahan"},
  {"kodu": "76", "aciklama": "Iğdır"},
  {"kodu": "77", "aciklama": "Yalova"},
  {"kodu": "78", "aciklama": "Karabük"},
  {"kodu": "79", "aciklama": "Kilis"},
  {"kodu": "80", "aciklama": "Osmaniye"},
  {"kodu": "81", "aciklama": "Düzce"},
];

List allCitiesOfTurkey = [
  {"aciklama": "Seçim Yapınız", "il": "0"},
  {"aciklama": "Seyhan", "il": "1"},
  {"aciklama": "Ceyhan", "il": "1"},
  {"aciklama": "Feke", "il": "1"},
  {"aciklama": "Karaisalı", "il": "1"},
  {"aciklama": "Karataş", "il": "1"},
  {"aciklama": "Kozan", "il": "1"},
  {"aciklama": "Pozantı", "il": "1"},
  {"aciklama": "Saimbeyli", "il": "1"},
  {"aciklama": "Tufanbeyli", "il": "1"},
  {"aciklama": "Yumurtalık", "il": "1"},
  {"aciklama": "Yüreğir", "il": "1"},
  {"aciklama": "Aladağ", "il": "1"},
  {"aciklama": "İmamoğlu", "il": "1"},
  {"aciklama": "Sarıçam", "il": "1"},
  {"aciklama": "Çukurova", "il": "1"},
  {"aciklama": "Adıyaman Merkez", "il": "2"},
  {"aciklama": "Besni", "il": "2"},
  {"aciklama": "Çelikhan", "il": "2"},
  {"aciklama": "Gerger", "il": "2"},
  {"aciklama": "Gölbaşı", "il": "2"},
  {"aciklama": "Kahta", "il": "2"},
  {"aciklama": "Samsat", "il": "2"},
  {"aciklama": "Sincik", "il": "2"},
  {"aciklama": "Tut", "il": "2"},
  {"aciklama": "Afyonkarahisar Merkez", "il": "3"},
  {"aciklama": "Bolvadin", "il": "3"},
  {"aciklama": "Çay", "il": "3"},
  {"aciklama": "Dazkırı", "il": "3"},
  {"aciklama": "Dinar", "il": "3"},
  {"aciklama": "Emirdağ", "il": "3"},
  {"aciklama": "İhsaniye", "il": "3"},
  {"aciklama": "Sandıklı", "il": "3"},
  {"aciklama": "Sinanpaşa", "il": "3"},
  {"aciklama": "Sultandağı", "il": "3"},
  {"aciklama": "Şuhut", "il": "3"},
  {"aciklama": "Başmakçı", "il": "3"},
  {"aciklama": "Bayat", "il": "3"},
  {"aciklama": "İscehisar", "il": "3"},
  {"aciklama": "Çobanlar", "il": "3"},
  {"aciklama": "Evciler", "il": "3"},
  {"aciklama": "Hocalar", "il": "3"},
  {"aciklama": "Kızılören", "il": "3"},
  {"aciklama": "Ağrı Merkez", "il": "4"},
  {"aciklama": "Diyadin", "il": "4"},
  {"aciklama": "Doğubayazıt", "il": "4"},
  {"aciklama": "Eleşkirt", "il": "4"},
  {"aciklama": "Hamur", "il": "4"},
  {"aciklama": "Patnos", "il": "4"},
  {"aciklama": "Taşlıçay", "il": "4"},
  {"aciklama": "Tutak", "il": "4"},
  {"aciklama": "Amasya Merkez", "il": "5"},
  {"aciklama": "Göynücek", "il": "5"},
  {"aciklama": "Gümüşhacıköy", "il": "5"},
  {"aciklama": "Merzifon", "il": "5"},
  {"aciklama": "Suluova", "il": "5"},
  {"aciklama": "Taşova", "il": "5"},
  {"aciklama": "Hamamözü", "il": "5"},
  {"aciklama": "Altındağ", "il": "6"},
  {"aciklama": "Ayaş", "il": "6"},
  {"aciklama": "Bala", "il": "6"},
  {"aciklama": "Beypazarı", "il": "6"},
  {"aciklama": "Çamlıdere", "il": "6"},
  {"aciklama": "Çankaya", "il": "6"},
  {"aciklama": "Çubuk", "il": "6"},
  {"aciklama": "Elmadağ", "il": "6"},
  {"aciklama": "Güdül", "il": "6"},
  {"aciklama": "Haymana", "il": "6"},
  {"aciklama": "Kalecik", "il": "6"},
  {"aciklama": "Kızılcahamam", "il": "6"},
  {"aciklama": "Nallıhan", "il": "6"},
  {"aciklama": "Polatlı", "il": "6"},
  {"aciklama": "Şereflikoçhisar", "il": "6"},
  {"aciklama": "Yenimahalle", "il": "6"},
  {"aciklama": "Gölbaşı", "il": "6"},
  {"aciklama": "Keçiören", "il": "6"},
  {"aciklama": "Mamak", "il": "6"},
  {"aciklama": "Sincan", "il": "6"},
  {"aciklama": "Kazan", "il": "6"},
  {"aciklama": "Akyurt", "il": "6"},
  {"aciklama": "Etimesgut", "il": "6"},
  {"aciklama": "Evren", "il": "6"},
  {"aciklama": "Pursaklar", "il": "6"},
  {"aciklama": "Akseki", "il": "7"},
  {"aciklama": "Alanya", "il": "7"},
  {"aciklama": "Elmalı", "il": "7"},
  {"aciklama": "Finike", "il": "7"},
  {"aciklama": "Gazipaşa", "il": "7"},
  {"aciklama": "Gündoğmuş", "il": "7"},
  {"aciklama": "Kaş", "il": "7"},
  {"aciklama": "Korkuteli", "il": "7"},
  {"aciklama": "Kumluca", "il": "7"},
  {"aciklama": "Manavgat", "il": "7"},
  {"aciklama": "Serik", "il": "7"},
  {"aciklama": "Demre", "il": "7"},
  {"aciklama": "İbradı", "il": "7"},
  {"aciklama": "Kemer", "il": "7"},
  {"aciklama": "Aksu", "il": "7"},
  {"aciklama": "Döşemealtı", "il": "7"},
  {"aciklama": "Kepez", "il": "7"},
  {"aciklama": "Konyaaltı", "il": "7"},
  {"aciklama": "Muratpaşa", "il": "7"},
  {"aciklama": "Ardanuç", "il": "8"},
  {"aciklama": "Arhavi", "il": "8"},
  {"aciklama": "Artvin Merkez", "il": "8"},
  {"aciklama": "Borçka", "il": "8"},
  {"aciklama": "Hopa", "il": "8"},
  {"aciklama": "Şavşat", "il": "8"},
  {"aciklama": "Yusufeli", "il": "8"},
  {"aciklama": "Murgul", "il": "8"},
  {"aciklama": "Bozdoğan", "il": "9"},
  {"aciklama": "Çine", "il": "9"},
  {"aciklama": "Germencik", "il": "9"},
  {"aciklama": "Karacasu", "il": "9"},
  {"aciklama": "Koçarlı", "il": "9"},
  {"aciklama": "Kuşadası", "il": "9"},
  {"aciklama": "Kuyucak", "il": "9"},
  {"aciklama": "Nazilli", "il": "9"},
  {"aciklama": "Söke", "il": "9"},
  {"aciklama": "Sultanhisar", "il": "9"},
  {"aciklama": "Yenipazar", "il": "9"},
  {"aciklama": "Buharkent", "il": "9"},
  {"aciklama": "İncirliova", "il": "9"},
  {"aciklama": "Karpuzlu", "il": "9"},
  {"aciklama": "Köşk", "il": "9"},
  {"aciklama": "Didim", "il": "9"},
  {"aciklama": "Efeler", "il": "9"},
  {"aciklama": "Ayvalık", "il": "10"},
  {"aciklama": "Balya", "il": "10"},
  {"aciklama": "Bandırma", "il": "10"},
  {"aciklama": "Bigadiç", "il": "10"},
  {"aciklama": "Burhaniye", "il": "10"},
  {"aciklama": "Dursunbey", "il": "10"},
  {"aciklama": "Edremit", "il": "10"},
  {"aciklama": "Erdek", "il": "10"},
  {"aciklama": "Gönen", "il": "10"},
  {"aciklama": "Havran", "il": "10"},
  {"aciklama": "İvrindi", "il": "10"},
  {"aciklama": "Kepsut", "il": "10"},
  {"aciklama": "Manyas", "il": "10"},
  {"aciklama": "Savaştepe", "il": "10"},
  {"aciklama": "Sındırgı", "il": "10"},
  {"aciklama": "Susurluk", "il": "10"},
  {"aciklama": "Marmara", "il": "10"},
  {"aciklama": "Gömeç", "il": "10"},
  {"aciklama": "Altıeylül", "il": "10"},
  {"aciklama": "Karesi", "il": "10"},
  {"aciklama": "Bilecik Merkez", "il": "11"},
  {"aciklama": "Bozüyük", "il": "11"},
  {"aciklama": "Gölpazarı", "il": "11"},
  {"aciklama": "Osmaneli", "il": "11"},
  {"aciklama": "Pazaryeri", "il": "11"},
  {"aciklama": "Söğüt", "il": "11"},
  {"aciklama": "Yenipazar", "il": "11"},
  {"aciklama": "İnhisar", "il": "11"},
  {"aciklama": "Bingöl Merkez", "il": "12"},
  {"aciklama": "Genç", "il": "12"},
  {"aciklama": "Karlıova", "il": "12"},
  {"aciklama": "Kiğı", "il": "12"},
  {"aciklama": "Solhan", "il": "12"},
  {"aciklama": "Adaklı", "il": "12"},
  {"aciklama": "Yayladere", "il": "12"},
  {"aciklama": "Yedisu", "il": "12"},
  {"aciklama": "Adilcevaz", "il": "13"},
  {"aciklama": "Ahlat", "il": "13"},
  {"aciklama": "Bitlis Merkez", "il": "13"},
  {"aciklama": "Hizan", "il": "13"},
  {"aciklama": "Mutki", "il": "13"},
  {"aciklama": "Tatvan", "il": "13"},
  {"aciklama": "Güroymak", "il": "13"},
  {"aciklama": "Bolu Merkez", "il": "14"},
  {"aciklama": "Gerede", "il": "14"},
  {"aciklama": "Göynük", "il": "14"},
  {"aciklama": "Kıbrıscık", "il": "14"},
  {"aciklama": "Mengen", "il": "14"},
  {"aciklama": "Mudurnu", "il": "14"},
  {"aciklama": "Seben", "il": "14"},
  {"aciklama": "Dörtdivan", "il": "14"},
  {"aciklama": "Yeniçağa", "il": "14"},
  {"aciklama": "Ağlasun", "il": "15"},
  {"aciklama": "Bucak", "il": "15"},
  {"aciklama": "Burdur Merkez", "il": "15"},
  {"aciklama": "Gölhisar", "il": "15"},
  {"aciklama": "Tefenni", "il": "15"},
  {"aciklama": "Yeşilova", "il": "15"},
  {"aciklama": "Karamanlı", "il": "15"},
  {"aciklama": "Kemer", "il": "15"},
  {"aciklama": "Altınyayla", "il": "15"},
  {"aciklama": "Çavdır", "il": "15"},
  {"aciklama": "Çeltikçi", "il": "15"},
  {"aciklama": "Gemlik", "il": "16"},
  {"aciklama": "İnegöl", "il": "16"},
  {"aciklama": "İznik", "il": "16"},
  {"aciklama": "Karacabey", "il": "16"},
  {"aciklama": "Keles", "il": "16"},
  {"aciklama": "Mudanya", "il": "16"},
  {"aciklama": "Mustafakemalpaşa", "il": "16"},
  {"aciklama": "Orhaneli", "il": "16"},
  {"aciklama": "Orhangazi", "il": "16"},
  {"aciklama": "Yenişehir", "il": "16"},
  {"aciklama": "Büyükorhan", "il": "16"},
  {"aciklama": "Harmancık", "il": "16"},
  {"aciklama": "Nilüfer", "il": "16"},
  {"aciklama": "Osmangazi", "il": "16"},
  {"aciklama": "Yıldırım", "il": "16"},
  {"aciklama": "Gürsu", "il": "16"},
  {"aciklama": "Kestel", "il": "16"},
  {"aciklama": "Ayvacık", "il": "17"},
  {"aciklama": "Bayramiç", "il": "17"},
  {"aciklama": "Biga", "il": "17"},
  {"aciklama": "Bozcaada", "il": "17"},
  {"aciklama": "Çan", "il": "17"},
  {"aciklama": "Çanakkale Merkez", "il": "17"},
  {"aciklama": "Eceabat", "il": "17"},
  {"aciklama": "Ezine", "il": "17"},
  {"aciklama": "Gelibolu", "il": "17"},
  {"aciklama": "Gökçeada", "il": "17"},
  {"aciklama": "Lapseki", "il": "17"},
  {"aciklama": "Yenice", "il": "17"},
  {"aciklama": "Çankırı Merkez", "il": "18"},
  {"aciklama": "Çerkeş", "il": "18"},
  {"aciklama": "Eldivan", "il": "18"},
  {"aciklama": "Ilgaz", "il": "18"},
  {"aciklama": "Kurşunlu", "il": "18"},
  {"aciklama": "Orta", "il": "18"},
  {"aciklama": "Şabanözü", "il": "18"},
  {"aciklama": "Yapraklı", "il": "18"},
  {"aciklama": "Atkaracalar", "il": "18"},
  {"aciklama": "Kızılırmak", "il": "18"},
  {"aciklama": "Bayramören", "il": "18"},
  {"aciklama": "Korgun", "il": "18"},
  {"aciklama": "Alaca", "il": "19"},
  {"aciklama": "Bayat", "il": "19"},
  {"aciklama": "Çorum Merkez", "il": "19"},
  {"aciklama": "İskilip", "il": "19"},
  {"aciklama": "Kargı", "il": "19"},
  {"aciklama": "Mecitözü", "il": "19"},
  {"aciklama": "Ortaköy", "il": "19"},
  {"aciklama": "Osmancık", "il": "19"},
  {"aciklama": "Sungurlu", "il": "19"},
  {"aciklama": "Boğazkale", "il": "19"},
  {"aciklama": "Uğurludağ", "il": "19"},
  {"aciklama": "Dodurga", "il": "19"},
  {"aciklama": "Laçin", "il": "19"},
  {"aciklama": "Oğuzlar", "il": "19"},
  {"aciklama": "Acıpayam", "il": "20"},
  {"aciklama": "Buldan", "il": "20"},
  {"aciklama": "Çal", "il": "20"},
  {"aciklama": "Çameli", "il": "20"},
  {"aciklama": "Çardak", "il": "20"},
  {"aciklama": "Çivril", "il": "20"},
  {"aciklama": "Güney", "il": "20"},
  {"aciklama": "Kale", "il": "20"},
  {"aciklama": "Sarayköy", "il": "20"},
  {"aciklama": "Tavas", "il": "20"},
  {"aciklama": "Babadağ", "il": "20"},
  {"aciklama": "Bekilli", "il": "20"},
  {"aciklama": "Honaz", "il": "20"},
  {"aciklama": "Serinhisar", "il": "20"},
  {"aciklama": "Pamukkale", "il": "20"},
  {"aciklama": "Baklan", "il": "20"},
  {"aciklama": "Beyağaç", "il": "20"},
  {"aciklama": "Bozkurt", "il": "20"},
  {"aciklama": "Merkezefendi", "il": "20"},
  {"aciklama": "Bismil", "il": "21"},
  {"aciklama": "Çermik", "il": "21"},
  {"aciklama": "Çınar", "il": "21"},
  {"aciklama": "Çüngüş", "il": "21"},
  {"aciklama": "Dicle", "il": "21"},
  {"aciklama": "Ergani", "il": "21"},
  {"aciklama": "Hani", "il": "21"},
  {"aciklama": "Hazro", "il": "21"},
  {"aciklama": "Kulp", "il": "21"},
  {"aciklama": "Lice", "il": "21"},
  {"aciklama": "Silvan", "il": "21"},
  {"aciklama": "Eğil", "il": "21"},
  {"aciklama": "Kocaköy", "il": "21"},
  {"aciklama": "Bağlar", "il": "21"},
  {"aciklama": "Kayapınar", "il": "21"},
  {"aciklama": "Sur", "il": "21"},
  {"aciklama": "Yenişehir", "il": "21"},
  {"aciklama": "Edirne Merkez", "il": "22"},
  {"aciklama": "Enez", "il": "22"},
  {"aciklama": "Havsa", "il": "22"},
  {"aciklama": "İpsala", "il": "22"},
  {"aciklama": "Keşan", "il": "22"},
  {"aciklama": "Lalapaşa", "il": "22"},
  {"aciklama": "Meriç", "il": "22"},
  {"aciklama": "Uzunköprü", "il": "22"},
  {"aciklama": "Süloğlu", "il": "22"},
  {"aciklama": "Ağın", "il": "23"},
  {"aciklama": "Baskil", "il": "23"},
  {"aciklama": "Elazığ Merkez", "il": "23"},
  {"aciklama": "Karakoçan", "il": "23"},
  {"aciklama": "Keban", "il": "23"},
  {"aciklama": "Maden", "il": "23"},
  {"aciklama": "Palu", "il": "23"},
  {"aciklama": "Sivrice", "il": "23"},
  {"aciklama": "Arıcak", "il": "23"},
  {"aciklama": "Kovancılar", "il": "23"},
  {"aciklama": "Alacakaya", "il": "23"},
  {"aciklama": "Çayırlı", "il": "24"},
  {"aciklama": "Erzincan Merkez", "il": "24"},
  {"aciklama": "İliç", "il": "24"},
  {"aciklama": "Kemah", "il": "24"},
  {"aciklama": "Kemaliye", "il": "24"},
  {"aciklama": "Refahiye", "il": "24"},
  {"aciklama": "Tercan", "il": "24"},
  {"aciklama": "Üzümlü", "il": "24"},
  {"aciklama": "Otlukbeli", "il": "24"},
  {"aciklama": "Aşkale", "il": "25"},
  {"aciklama": "Çat", "il": "25"},
  {"aciklama": "Hınıs", "il": "25"},
  {"aciklama": "Horasan", "il": "25"},
  {"aciklama": "İspir", "il": "25"},
  {"aciklama": "Karayazı", "il": "25"},
  {"aciklama": "Narman", "il": "25"},
  {"aciklama": "Oltu", "il": "25"},
  {"aciklama": "Olur", "il": "25"},
  {"aciklama": "Pasinler", "il": "25"},
  {"aciklama": "Şenkaya", "il": "25"},
  {"aciklama": "Tekman", "il": "25"},
  {"aciklama": "Tortum", "il": "25"},
  {"aciklama": "Karaçoban", "il": "25"},
  {"aciklama": "Uzundere", "il": "25"},
  {"aciklama": "Pazaryolu", "il": "25"},
  {"aciklama": "Aziziye", "il": "25"},
  {"aciklama": "Köprüköy", "il": "25"},
  {"aciklama": "Palandöken", "il": "25"},
  {"aciklama": "Yakutiye", "il": "25"},
  {"aciklama": "Çifteler", "il": "26"},
  {"aciklama": "Mahmudiye", "il": "26"},
  {"aciklama": "Mihalıççık", "il": "26"},
  {"aciklama": "Sarıcakaya", "il": "26"},
  {"aciklama": "Seyitgazi", "il": "26"},
  {"aciklama": "Sivrihisar", "il": "26"},
  {"aciklama": "Alpu", "il": "26"},
  {"aciklama": "Beylikova", "il": "26"},
  {"aciklama": "İnönü", "il": "26"},
  {"aciklama": "Günyüzü", "il": "26"},
  {"aciklama": "Han", "il": "26"},
  {"aciklama": "Mihalgazi", "il": "26"},
  {"aciklama": "Odunpazarı", "il": "26"},
  {"aciklama": "Tepebaşı", "il": "26"},
  {"aciklama": "Araban", "il": "27"},
  {"aciklama": "İslahiye", "il": "27"},
  {"aciklama": "Nizip", "il": "27"},
  {"aciklama": "Oğuzeli", "il": "27"},
  {"aciklama": "Yavuzeli", "il": "27"},
  {"aciklama": "Şahinbey", "il": "27"},
  {"aciklama": "Şehitkamil", "il": "27"},
  {"aciklama": "Karkamış", "il": "27"},
  {"aciklama": "Nurdağı", "il": "27"},
  {"aciklama": "Alucra", "il": "28"},
  {"aciklama": "Bulancak", "il": "28"},
  {"aciklama": "Dereli", "il": "28"},
  {"aciklama": "Espiye", "il": "28"},
  {"aciklama": "Eynesil", "il": "28"},
  {"aciklama": "Giresun Merkez", "il": "28"},
  {"aciklama": "Görele", "il": "28"},
  {"aciklama": "Keşap", "il": "28"},
  {"aciklama": "Şebinkarahisar", "il": "28"},
  {"aciklama": "Tirebolu", "il": "28"},
  {"aciklama": "Piraziz", "il": "28"},
  {"aciklama": "Yağlıdere", "il": "28"},
  {"aciklama": "Çamoluk", "il": "28"},
  {"aciklama": "Çanakçı", "il": "28"},
  {"aciklama": "Doğankent", "il": "28"},
  {"aciklama": "Güce", "il": "28"},
  {"aciklama": "Gümüşhane Merkez", "il": "29"},
  {"aciklama": "Kelkit", "il": "29"},
  {"aciklama": "Şiran", "il": "29"},
  {"aciklama": "Torul", "il": "29"},
  {"aciklama": "Köse", "il": "29"},
  {"aciklama": "Kürtün", "il": "29"},
  {"aciklama": "Çukurca", "il": "30"},
  {"aciklama": "Hakkari Merkez", "il": "30"},
  {"aciklama": "Şemdinli", "il": "30"},
  {"aciklama": "Yüksekova", "il": "30"},
  {"aciklama": "Altınözü", "il": "31"},
  {"aciklama": "Dörtyol", "il": "31"},
  {"aciklama": "Hassa", "il": "31"},
  {"aciklama": "İskenderun", "il": "31"},
  {"aciklama": "Kırıkhan", "il": "31"},
  {"aciklama": "Reyhanlı", "il": "31"},
  {"aciklama": "Samandağ", "il": "31"},
  {"aciklama": "Yayladağı", "il": "31"},
  {"aciklama": "Erzin", "il": "31"},
  {"aciklama": "Belen", "il": "31"},
  {"aciklama": "Kumlu", "il": "31"},
  {"aciklama": "Antakya", "il": "31"},
  {"aciklama": "Arsuz", "il": "31"},
  {"aciklama": "Defne", "il": "31"},
  {"aciklama": "Payas", "il": "31"},
  {"aciklama": "Atabey", "il": "32"},
  {"aciklama": "Eğirdir", "il": "32"},
  {"aciklama": "Gelendost", "il": "32"},
  {"aciklama": "Isparta Merkez", "il": "32"},
  {"aciklama": "Keçiborlu", "il": "32"},
  {"aciklama": "Senirkent", "il": "32"},
  {"aciklama": "Sütçüler", "il": "32"},
  {"aciklama": "Şarkikaraağaç", "il": "32"},
  {"aciklama": "Uluborlu", "il": "32"},
  {"aciklama": "Yalvaç", "il": "32"},
  {"aciklama": "Aksu", "il": "32"},
  {"aciklama": "Gönen", "il": "32"},
  {"aciklama": "Yenişarbademli", "il": "32"},
  {"aciklama": "Anamur", "il": "33"},
  {"aciklama": "Erdemli", "il": "33"},
  {"aciklama": "Gülnar", "il": "33"},
  {"aciklama": "Mut", "il": "33"},
  {"aciklama": "Silifke", "il": "33"},
  {"aciklama": "Tarsus", "il": "33"},
  {"aciklama": "Aydıncık", "il": "33"},
  {"aciklama": "Bozyazı", "il": "33"},
  {"aciklama": "Çamlıyayla", "il": "33"},
  {"aciklama": "Akdeniz", "il": "33"},
  {"aciklama": "Mezitli", "il": "33"},
  {"aciklama": "Toroslar", "il": "33"},
  {"aciklama": "Yenişehir", "il": "33"},
  {"aciklama": "Adalar", "il": "34"},
  {"aciklama": "Bakırköy", "il": "34"},
  {"aciklama": "Beşiktaş", "il": "34"},
  {"aciklama": "Beykoz", "il": "34"},
  {"aciklama": "Beyoğlu", "il": "34"},
  {"aciklama": "Çatalca", "il": "34"},
  {"aciklama": "Eyüp", "il": "34"},
  {"aciklama": "Fatih", "il": "34"},
  {"aciklama": "Gaziosmanpaşa", "il": "34"},
  {"aciklama": "Kadıköy", "il": "34"},
  {"aciklama": "Kartal", "il": "34"},
  {"aciklama": "Sarıyer", "il": "34"},
  {"aciklama": "Silivri", "il": "34"},
  {"aciklama": "Şile", "il": "34"},
  {"aciklama": "Şişli", "il": "34"},
  {"aciklama": "Üsküdar", "il": "34"},
  {"aciklama": "Zeytinburnu", "il": "34"},
  {"aciklama": "Büyükçekmece", "il": "34"},
  {"aciklama": "Kağıthane", "il": "34"},
  {"aciklama": "Küçükçekmece", "il": "34"},
  {"aciklama": "Pendik", "il": "34"},
  {"aciklama": "Ümraniye", "il": "34"},
  {"aciklama": "Bayrampaşa", "il": "34"},
  {"aciklama": "Avcılar", "il": "34"},
  {"aciklama": "Bağcılar", "il": "34"},
  {"aciklama": "Bahçelievler", "il": "34"},
  {"aciklama": "Güngören", "il": "34"},
  {"aciklama": "Maltepe", "il": "34"},
  {"aciklama": "Sultanbeyli", "il": "34"},
  {"aciklama": "Tuzla", "il": "34"},
  {"aciklama": "Esenler", "il": "34"},
  {"aciklama": "Arnavutköy", "il": "34"},
  {"aciklama": "Ataşehir", "il": "34"},
  {"aciklama": "Başakşehir", "il": "34"},
  {"aciklama": "Beylikdüzü", "il": "34"},
  {"aciklama": "Çekmeköy", "il": "34"},
  {"aciklama": "Esenyurt", "il": "34"},
  {"aciklama": "Sancaktepe", "il": "34"},
  {"aciklama": "Sultangazi", "il": "34"},
  {"aciklama": "Aliağa", "il": "35"},
  {"aciklama": "Bayındır", "il": "35"},
  {"aciklama": "Bergama", "il": "35"},
  {"aciklama": "Bornova", "il": "35"},
  {"aciklama": "Çeşme", "il": "35"},
  {"aciklama": "Dikili", "il": "35"},
  {"aciklama": "Foça", "il": "35"},
  {"aciklama": "Karaburun", "il": "35"},
  {"aciklama": "Karşıyaka", "il": "35"},
  {"aciklama": "Kemalpaşa", "il": "35"},
  {"aciklama": "Kınık", "il": "35"},
  {"aciklama": "Kiraz", "il": "35"},
  {"aciklama": "Menemen", "il": "35"},
  {"aciklama": "Ödemiş", "il": "35"},
  {"aciklama": "Seferihisar", "il": "35"},
  {"aciklama": "Selçuk", "il": "35"},
  {"aciklama": "Tire", "il": "35"},
  {"aciklama": "Torbalı", "il": "35"},
  {"aciklama": "Urla", "il": "35"},
  {"aciklama": "Beydağ", "il": "35"},
  {"aciklama": "Buca", "il": "35"},
  {"aciklama": "Konak", "il": "35"},
  {"aciklama": "Menderes", "il": "35"},
  {"aciklama": "Balçova", "il": "35"},
  {"aciklama": "Çiğli", "il": "35"},
  {"aciklama": "Gaziemir", "il": "35"},
  {"aciklama": "Narlıdere", "il": "35"},
  {"aciklama": "Güzelbahçe", "il": "35"},
  {"aciklama": "Bayraklı", "il": "35"},
  {"aciklama": "Karabağlar", "il": "35"},
  {"aciklama": "Arpaçay", "il": "36"},
  {"aciklama": "Digor", "il": "36"},
  {"aciklama": "Kağızman", "il": "36"},
  {"aciklama": "Kars Merkez", "il": "36"},
  {"aciklama": "Sarıkamış", "il": "36"},
  {"aciklama": "Selim", "il": "36"},
  {"aciklama": "Susuz", "il": "36"},
  {"aciklama": "Akyaka", "il": "36"},
  {"aciklama": "Abana", "il": "37"},
  {"aciklama": "Araç", "il": "37"},
  {"aciklama": "Azdavay", "il": "37"},
  {"aciklama": "Bozkurt", "il": "37"},
  {"aciklama": "Cide", "il": "37"},
  {"aciklama": "Çatalzeytin", "il": "37"},
  {"aciklama": "Daday", "il": "37"},
  {"aciklama": "Devrekani", "il": "37"},
  {"aciklama": "İnebolu", "il": "37"},
  {"aciklama": "Kastamonu Merkez", "il": "37"},
  {"aciklama": "Küre", "il": "37"},
  {"aciklama": "Taşköprü", "il": "37"},
  {"aciklama": "Tosya", "il": "37"},
  {"aciklama": "İhsangazi", "il": "37"},
  {"aciklama": "Pınarbaşı", "il": "37"},
  {"aciklama": "Şenpazar", "il": "37"},
  {"aciklama": "Ağlı", "il": "37"},
  {"aciklama": "Doğanyurt", "il": "37"},
  {"aciklama": "Hanönü", "il": "37"},
  {"aciklama": "Seydiler", "il": "37"},
  {"aciklama": "Bünyan", "il": "38"},
  {"aciklama": "Develi", "il": "38"},
  {"aciklama": "Felahiye", "il": "38"},
  {"aciklama": "İncesu", "il": "38"},
  {"aciklama": "Pınarbaşı", "il": "38"},
  {"aciklama": "Sarıoğlan", "il": "38"},
  {"aciklama": "Sarız", "il": "38"},
  {"aciklama": "Tomarza", "il": "38"},
  {"aciklama": "Yahyalı", "il": "38"},
  {"aciklama": "Yeşilhisar", "il": "38"},
  {"aciklama": "Akkışla", "il": "38"},
  {"aciklama": "Talas", "il": "38"},
  {"aciklama": "Kocasinan", "il": "38"},
  {"aciklama": "Melikgazi", "il": "38"},
  {"aciklama": "Hacılar", "il": "38"},
  {"aciklama": "Özvatan", "il": "38"},
  {"aciklama": "Babaeski", "il": "39"},
  {"aciklama": "Demirköy", "il": "39"},
  {"aciklama": "Kırklareli Merkez", "il": "39"},
  {"aciklama": "Kofçaz", "il": "39"},
  {"aciklama": "Lüleburgaz", "il": "39"},
  {"aciklama": "Pehlivanköy", "il": "39"},
  {"aciklama": "Pınarhisar", "il": "39"},
  {"aciklama": "Vize", "il": "39"},
  {"aciklama": "Çiçekdağı", "il": "40"},
  {"aciklama": "Kaman", "il": "40"},
  {"aciklama": "Kırşehir Merkez", "il": "40"},
  {"aciklama": "Mucur", "il": "40"},
  {"aciklama": "Akpınar", "il": "40"},
  {"aciklama": "Akçakent", "il": "40"},
  {"aciklama": "Boztepe", "il": "40"},
  {"aciklama": "Gebze", "il": "41"},
  {"aciklama": "Gölcük", "il": "41"},
  {"aciklama": "Kandıra", "il": "41"},
  {"aciklama": "Karamürsel", "il": "41"},
  {"aciklama": "Körfez", "il": "41"},
  {"aciklama": "Derince", "il": "41"},
  {"aciklama": "Başiskele", "il": "41"},
  {"aciklama": "Çayırova", "il": "41"},
  {"aciklama": "Darıca", "il": "41"},
  {"aciklama": "Dilovası", "il": "41"},
  {"aciklama": "İzmit", "il": "41"},
  {"aciklama": "Kartepe", "il": "41"},
  {"aciklama": "Akşehir", "il": "42"},
  {"aciklama": "Beyşehir", "il": "42"},
  {"aciklama": "Bozkır", "il": "42"},
  {"aciklama": "Cihanbeyli", "il": "42"},
  {"aciklama": "Çumra", "il": "42"},
  {"aciklama": "Doğanhisar", "il": "42"},
  {"aciklama": "Ereğli", "il": "42"},
  {"aciklama": "Hadim", "il": "42"},
  {"aciklama": "Ilgın", "il": "42"},
  {"aciklama": "Kadınhanı", "il": "42"},
  {"aciklama": "Karapınar", "il": "42"},
  {"aciklama": "Kulu", "il": "42"},
  {"aciklama": "Sarayönü", "il": "42"},
  {"aciklama": "Seydişehir", "il": "42"},
  {"aciklama": "Yunak", "il": "42"},
  {"aciklama": "Akören", "il": "42"},
  {"aciklama": "Altınekin", "il": "42"},
  {"aciklama": "Derebucak", "il": "42"},
  {"aciklama": "Hüyük", "il": "42"},
  {"aciklama": "Karatay", "il": "42"},
  {"aciklama": "Meram", "il": "42"},
  {"aciklama": "Selçuklu", "il": "42"},
  {"aciklama": "Taşkent", "il": "42"},
  {"aciklama": "Ahırlı", "il": "42"},
  {"aciklama": "Çeltik", "il": "42"},
  {"aciklama": "Derbent", "il": "42"},
  {"aciklama": "Emirgazi", "il": "42"},
  {"aciklama": "Güneysınır", "il": "42"},
  {"aciklama": "Halkapınar", "il": "42"},
  {"aciklama": "Tuzlukçu", "il": "42"},
  {"aciklama": "Yalıhüyük", "il": "42"},
  {"aciklama": "Altıntaş", "il": "43"},
  {"aciklama": "Domaniç", "il": "43"},
  {"aciklama": "Emet", "il": "43"},
  {"aciklama": "Gediz", "il": "43"},
  {"aciklama": "Kütahya Merkez", "il": "43"},
  {"aciklama": "Simav", "il": "43"},
  {"aciklama": "Tavşanlı", "il": "43"},
  {"aciklama": "Aslanapa", "il": "43"},
  {"aciklama": "Dumlupınar", "il": "43"},
  {"aciklama": "Hisarcık", "il": "43"},
  {"aciklama": "Şaphane", "il": "43"},
  {"aciklama": "Çavdarhisar", "il": "43"},
  {"aciklama": "Pazarlar", "il": "43"},
  {"aciklama": "Akçadağ", "il": "44"},
  {"aciklama": "Arapgir", "il": "44"},
  {"aciklama": "Arguvan", "il": "44"},
  {"aciklama": "Darende", "il": "44"},
  {"aciklama": "Doğanşehir", "il": "44"},
  {"aciklama": "Hekimhan", "il": "44"},
  {"aciklama": "Pütürge", "il": "44"},
  {"aciklama": "Yeşilyurt", "il": "44"},
  {"aciklama": "Battalgazi", "il": "44"},
  {"aciklama": "Doğanyol", "il": "44"},
  {"aciklama": "Kale", "il": "44"},
  {"aciklama": "Kuluncak", "il": "44"},
  {"aciklama": "Yazıhan", "il": "44"},
  {"aciklama": "Akhisar", "il": "45"},
  {"aciklama": "Alaşehir", "il": "45"},
  {"aciklama": "Demirci", "il": "45"},
  {"aciklama": "Gördes", "il": "45"},
  {"aciklama": "Kırkağaç", "il": "45"},
  {"aciklama": "Kula", "il": "45"},
  {"aciklama": "Salihli", "il": "45"},
  {"aciklama": "Sarıgöl", "il": "45"},
  {"aciklama": "Saruhanlı", "il": "45"},
  {"aciklama": "Selendi", "il": "45"},
  {"aciklama": "Soma", "il": "45"},
  {"aciklama": "Turgutlu", "il": "45"},
  {"aciklama": "Ahmetli", "il": "45"},
  {"aciklama": "Gölmarmara", "il": "45"},
  {"aciklama": "Köprübaşı", "il": "45"},
  {"aciklama": "Şehzadeler", "il": "45"},
  {"aciklama": "Yunusemre", "il": "45"},
  {"aciklama": "Afşin", "il": "46"},
  {"aciklama": "Andırın", "il": "46"},
  {"aciklama": "Elbistan", "il": "46"},
  {"aciklama": "Göksun", "il": "46"},
  {"aciklama": "Pazarcık", "il": "46"},
  {"aciklama": "Türkoğlu", "il": "46"},
  {"aciklama": "Çağlayancerit", "il": "46"},
  {"aciklama": "Ekinözü", "il": "46"},
  {"aciklama": "Nurhak", "il": "46"},
  {"aciklama": "Dulkadiroğlu", "il": "46"},
  {"aciklama": "Onikişubat", "il": "46"},
  {"aciklama": "Derik", "il": "47"},
  {"aciklama": "Kızıltepe", "il": "47"},
  {"aciklama": "Mazıdağı", "il": "47"},
  {"aciklama": "Midyat", "il": "47"},
  {"aciklama": "Nusaybin", "il": "47"},
  {"aciklama": "Ömerli", "il": "47"},
  {"aciklama": "Savur", "il": "47"},
  {"aciklama": "Dargeçit", "il": "47"},
  {"aciklama": "Yeşilli", "il": "47"},
  {"aciklama": "Artuklu", "il": "47"},
  {"aciklama": "Bodrum", "il": "48"},
  {"aciklama": "Datça", "il": "48"},
  {"aciklama": "Fethiye", "il": "48"},
  {"aciklama": "Köyceğiz", "il": "48"},
  {"aciklama": "Marmaris", "il": "48"},
  {"aciklama": "Milas", "il": "48"},
  {"aciklama": "Ula", "il": "48"},
  {"aciklama": "Yatağan", "il": "48"},
  {"aciklama": "Dalaman", "il": "48"},
  {"aciklama": "Ortaca", "il": "48"},
  {"aciklama": "Kavaklıdere", "il": "48"},
  {"aciklama": "Menteşe", "il": "48"},
  {"aciklama": "Seydikemer", "il": "48"},
  {"aciklama": "Bulanık", "il": "49"},
  {"aciklama": "Malazgirt", "il": "49"},
  {"aciklama": "Muş Merkez", "il": "49"},
  {"aciklama": "Varto", "il": "49"},
  {"aciklama": "Hasköy", "il": "49"},
  {"aciklama": "Korkut", "il": "49"},
  {"aciklama": "Avanos", "il": "50"},
  {"aciklama": "Derinkuyu", "il": "50"},
  {"aciklama": "Gülşehir", "il": "50"},
  {"aciklama": "Hacıbektaş", "il": "50"},
  {"aciklama": "Kozaklı", "il": "50"},
  {"aciklama": "Nevşehir Merkez", "il": "50"},
  {"aciklama": "Ürgüp", "il": "50"},
  {"aciklama": "Acıgöl", "il": "50"},
  {"aciklama": "Bor", "il": "51"},
  {"aciklama": "Çamardı", "il": "51"},
  {"aciklama": "Niğde Merkez", "il": "51"},
  {"aciklama": "Ulukışla", "il": "51"},
  {"aciklama": "Altunhisar", "il": "51"},
  {"aciklama": "Çiftlik", "il": "51"},
  {"aciklama": "Akkuş", "il": "52"},
  {"aciklama": "Aybastı", "il": "52"},
  {"aciklama": "Fatsa", "il": "52"},
  {"aciklama": "Gölköy", "il": "52"},
  {"aciklama": "Korgan", "il": "52"},
  {"aciklama": "Kumru", "il": "52"},
  {"aciklama": "Mesudiye", "il": "52"},
  {"aciklama": "Perşembe", "il": "52"},
  {"aciklama": "Ulubey", "il": "52"},
  {"aciklama": "Ünye", "il": "52"},
  {"aciklama": "Gülyalı", "il": "52"},
  {"aciklama": "Gürgentepe", "il": "52"},
  {"aciklama": "Çamaş", "il": "52"},
  {"aciklama": "Çatalpınar", "il": "52"},
  {"aciklama": "Çaybaşı", "il": "52"},
  {"aciklama": "İkizce", "il": "52"},
  {"aciklama": "Kabadüz", "il": "52"},
  {"aciklama": "Kabataş", "il": "52"},
  {"aciklama": "Altınordu", "il": "52"},
  {"aciklama": "Ardeşen", "il": "53"},
  {"aciklama": "Çamlıhemşin", "il": "53"},
  {"aciklama": "Çayeli", "il": "53"},
  {"aciklama": "Fındıklı", "il": "53"},
  {"aciklama": "İkizdere", "il": "53"},
  {"aciklama": "Kalkandere", "il": "53"},
  {"aciklama": "Pazar", "il": "53"},
  {"aciklama": "Rize Merkez", "il": "53"},
  {"aciklama": "Güneysu", "il": "53"},
  {"aciklama": "Derepazarı", "il": "53"},
  {"aciklama": "Hemşin", "il": "53"},
  {"aciklama": "İyidere", "il": "53"},
  {"aciklama": "Akyazı", "il": "54"},
  {"aciklama": "Geyve", "il": "54"},
  {"aciklama": "Hendek", "il": "54"},
  {"aciklama": "Karasu", "il": "54"},
  {"aciklama": "Kaynarca", "il": "54"},
  {"aciklama": "Sapanca", "il": "54"},
  {"aciklama": "Kocaali", "il": "54"},
  {"aciklama": "Pamukova", "il": "54"},
  {"aciklama": "Taraklı", "il": "54"},
  {"aciklama": "Ferizli", "il": "54"},
  {"aciklama": "Karapürçek", "il": "54"},
  {"aciklama": "Söğütlü", "il": "54"},
  {"aciklama": "Adapazarı", "il": "54"},
  {"aciklama": "Arifiye", "il": "54"},
  {"aciklama": "Erenler", "il": "54"},
  {"aciklama": "Serdivan", "il": "54"},
  {"aciklama": "Alaçam", "il": "55"},
  {"aciklama": "Bafra", "il": "55"},
  {"aciklama": "Çarşamba", "il": "55"},
  {"aciklama": "Havza", "il": "55"},
  {"aciklama": "Kavak", "il": "55"},
  {"aciklama": "Ladik", "il": "55"},
  {"aciklama": "Terme", "il": "55"},
  {"aciklama": "Vezirköprü", "il": "55"},
  {"aciklama": "Asarcık", "il": "55"},
  {"aciklama": "19 Mayıs", "il": "55"},
  {"aciklama": "Salıpazarı", "il": "55"},
  {"aciklama": "Tekkeköy", "il": "55"},
  {"aciklama": "Ayvacık", "il": "55"},
  {"aciklama": "Yakakent", "il": "55"},
  {"aciklama": "Atakum", "il": "55"},
  {"aciklama": "Canik", "il": "55"},
  {"aciklama": "İlkadım", "il": "55"},
  {"aciklama": "Baykan", "il": "56"},
  {"aciklama": "Eruh", "il": "56"},
  {"aciklama": "Kurtalan", "il": "56"},
  {"aciklama": "Pervari", "il": "56"},
  {"aciklama": "Siirt Merkez", "il": "56"},
  {"aciklama": "Şirvan", "il": "56"},
  {"aciklama": "Tillo", "il": "56"},
  {"aciklama": "Ayancık", "il": "57"},
  {"aciklama": "Boyabat", "il": "57"},
  {"aciklama": "Durağan", "il": "57"},
  {"aciklama": "Erfelek", "il": "57"},
  {"aciklama": "Gerze", "il": "57"},
  {"aciklama": "Sinop Merkez", "il": "57"},
  {"aciklama": "Türkeli", "il": "57"},
  {"aciklama": "Dikmen", "il": "57"},
  {"aciklama": "Saraydüzü", "il": "57"},
  {"aciklama": "Divriği", "il": "58"},
  {"aciklama": "Gemerek", "il": "58"},
  {"aciklama": "Gürün", "il": "58"},
  {"aciklama": "Hafik", "il": "58"},
  {"aciklama": "İmranlı", "il": "58"},
  {"aciklama": "Kangal", "il": "58"},
  {"aciklama": "Koyulhisar", "il": "58"},
  {"aciklama": "Sivas Merkez", "il": "58"},
  {"aciklama": "Suşehri", "il": "58"},
  {"aciklama": "Şarkışla", "il": "58"},
  {"aciklama": "Yıldızeli", "il": "58"},
  {"aciklama": "Zara", "il": "58"},
  {"aciklama": "Akıncılar", "il": "58"},
  {"aciklama": "Altınyayla", "il": "58"},
  {"aciklama": "Doğanşar", "il": "58"},
  {"aciklama": "Gölova", "il": "58"},
  {"aciklama": "Ulaş", "il": "58"},
  {"aciklama": "Çerkezköy", "il": "59"},
  {"aciklama": "Çorlu", "il": "59"},
  {"aciklama": "Hayrabolu", "il": "59"},
  {"aciklama": "Malkara", "il": "59"},
  {"aciklama": "Muratlı", "il": "59"},
  {"aciklama": "Saray", "il": "59"},
  {"aciklama": "Şarköy", "il": "59"},
  {"aciklama": "Marmaraereğlisi", "il": "59"},
  {"aciklama": "Ergene", "il": "59"},
  {"aciklama": "Kapaklı", "il": "59"},
  {"aciklama": "Süleymanpaşa", "il": "59"},
  {"aciklama": "Almus", "il": "60"},
  {"aciklama": "Artova", "il": "60"},
  {"aciklama": "Erbaa", "il": "60"},
  {"aciklama": "Niksar", "il": "60"},
  {"aciklama": "Reşadiye", "il": "60"},
  {"aciklama": "Tokat Merkez", "il": "60"},
  {"aciklama": "Turhal", "il": "60"},
  {"aciklama": "Zile", "il": "60"},
  {"aciklama": "Pazar", "il": "60"},
  {"aciklama": "Yeşilyurt", "il": "60"},
  {"aciklama": "Başçiftlik", "il": "60"},
  {"aciklama": "Sulusaray", "il": "60"},
  {"aciklama": "Akçaabat", "il": "61"},
  {"aciklama": "Araklı", "il": "61"},
  {"aciklama": "Arsin", "il": "61"},
  {"aciklama": "Çaykara", "il": "61"},
  {"aciklama": "Maçka", "il": "61"},
  {"aciklama": "Of", "il": "61"},
  {"aciklama": "Sürmene", "il": "61"},
  {"aciklama": "Tonya", "il": "61"},
  {"aciklama": "Vakfıkebir", "il": "61"},
  {"aciklama": "Yomra", "il": "61"},
  {"aciklama": "Beşikdüzü", "il": "61"},
  {"aciklama": "Şalpazarı", "il": "61"},
  {"aciklama": "Çarşıbaşı", "il": "61"},
  {"aciklama": "Dernekpazarı", "il": "61"},
  {"aciklama": "Düzköy", "il": "61"},
  {"aciklama": "Hayrat", "il": "61"},
  {"aciklama": "Köprübaşı", "il": "61"},
  {"aciklama": "Ortahisar", "il": "61"},
  {"aciklama": "Çemişgezek", "il": "62"},
  {"aciklama": "Hozat", "il": "62"},
  {"aciklama": "Mazgirt", "il": "62"},
  {"aciklama": "Nazımiye", "il": "62"},
  {"aciklama": "Ovacık", "il": "62"},
  {"aciklama": "Pertek", "il": "62"},
  {"aciklama": "Pülümür", "il": "62"},
  {"aciklama": "Tunceli Merkez", "il": "62"},
  {"aciklama": "Akçakale", "il": "63"},
  {"aciklama": "Birecik", "il": "63"},
  {"aciklama": "Bozova", "il": "63"},
  {"aciklama": "Ceylanpınar", "il": "63"},
  {"aciklama": "Halfeti", "il": "63"},
  {"aciklama": "Hilvan", "il": "63"},
  {"aciklama": "Siverek", "il": "63"},
  {"aciklama": "Suruç", "il": "63"},
  {"aciklama": "Viranşehir", "il": "63"},
  {"aciklama": "Harran", "il": "63"},
  {"aciklama": "Eyyübiye", "il": "63"},
  {"aciklama": "Haliliye", "il": "63"},
  {"aciklama": "Karaköprü", "il": "63"},
  {"aciklama": "Banaz", "il": "64"},
  {"aciklama": "Eşme", "il": "64"},
  {"aciklama": "Karahallı", "il": "64"},
  {"aciklama": "Sivaslı", "il": "64"},
  {"aciklama": "Ulubey", "il": "64"},
  {"aciklama": "Uşak Merkez", "il": "64"},
  {"aciklama": "Başkale", "il": "65"},
  {"aciklama": "Çatak", "il": "65"},
  {"aciklama": "Erciş", "il": "65"},
  {"aciklama": "Gevaş", "il": "65"},
  {"aciklama": "Gürpınar", "il": "65"},
  {"aciklama": "Muradiye", "il": "65"},
  {"aciklama": "Özalp", "il": "65"},
  {"aciklama": "Bahçesaray", "il": "65"},
  {"aciklama": "Çaldıran", "il": "65"},
  {"aciklama": "Edremit", "il": "65"},
  {"aciklama": "Saray", "il": "65"},
  {"aciklama": "İpekyolu", "il": "65"},
  {"aciklama": "Tuşba", "il": "65"},
  {"aciklama": "Akdağmadeni", "il": "66"},
  {"aciklama": "Boğazlıyan", "il": "66"},
  {"aciklama": "Çayıralan", "il": "66"},
  {"aciklama": "Çekerek", "il": "66"},
  {"aciklama": "Sarıkaya", "il": "66"},
  {"aciklama": "Sorgun", "il": "66"},
  {"aciklama": "Şefaatli", "il": "66"},
  {"aciklama": "Yerköy", "il": "66"},
  {"aciklama": "Yozgat Merkez", "il": "66"},
  {"aciklama": "Aydıncıkt", "il": "66"},
  {"aciklama": "Çandır", "il": "66"},
  {"aciklama": "Kadışehri", "il": "66"},
  {"aciklama": "Saraykent", "il": "66"},
  {"aciklama": "Yenifakılı", "il": "66"},
  {"aciklama": "Çaycuma", "il": "67"},
  {"aciklama": "Devrek", "il": "67"},
  {"aciklama": "Ereğli", "il": "67"},
  {"aciklama": "Zonguldak Merkez", "il": "67"},
  {"aciklama": "Alaplı", "il": "67"},
  {"aciklama": "Gökçebey", "il": "67"},
  {"aciklama": "Kilimli", "il": "67"},
  {"aciklama": "Kozlu", "il": "67"},
  {"aciklama": "Aksaray Merkez", "il": "68"},
  {"aciklama": "Ortaköy", "il": "68"},
  {"aciklama": "Ağaçören", "il": "68"},
  {"aciklama": "Güzelyurt", "il": "68"},
  {"aciklama": "Sarıyahşi", "il": "68"},
  {"aciklama": "Eskil", "il": "68"},
  {"aciklama": "Gülağaç", "il": "68"},
  {"aciklama": "Bayburt Merkez", "il": "69"},
  {"aciklama": "Aydıntepe", "il": "69"},
  {"aciklama": "Demirözü", "il": "69"},
  {"aciklama": "Ermenek", "il": "70"},
  {"aciklama": "Karaman Merkez", "il": "70"},
  {"aciklama": "Ayrancı", "il": "70"},
  {"aciklama": "Kazımkarabekir", "il": "70"},
  {"aciklama": "Başyayla", "il": "70"},
  {"aciklama": "Sarıveliler", "il": "70"},
  {"aciklama": "Delice", "il": "71"},
  {"aciklama": "Keskin", "il": "71"},
  {"aciklama": "Kırıkkale Merkez", "il": "71"},
  {"aciklama": "Sulakyurt", "il": "71"},
  {"aciklama": "Bahşili", "il": "71"},
  {"aciklama": "Balışeyh", "il": "71"},
  {"aciklama": "Çelebi", "il": "71"},
  {"aciklama": "Karakeçili", "il": "71"},
  {"aciklama": "Yahşihan", "il": "71"},
  {"aciklama": "Batman Merkez", "il": "72"},
  {"aciklama": "Beşiri", "il": "72"},
  {"aciklama": "Gercüş", "il": "72"},
  {"aciklama": "Kozluk", "il": "72"},
  {"aciklama": "Sason", "il": "72"},
  {"aciklama": "Hasankeyf", "il": "72"},
  {"aciklama": "Beytüşşebap", "il": "73"},
  {"aciklama": "Cizre", "il": "73"},
  {"aciklama": "İdil", "il": "73"},
  {"aciklama": "Silopi", "il": "73"},
  {"aciklama": "Şırnak Merkez", "il": "73"},
  {"aciklama": "Uludere", "il": "73"},
  {"aciklama": "Güçlükonak", "il": "73"},
  {"aciklama": "Bartın Merkez", "il": "74"},
  {"aciklama": "Kurucaşile", "il": "74"},
  {"aciklama": "Ulus", "il": "74"},
  {"aciklama": "Amasra", "il": "74"},
  {"aciklama": "Ardahan Merkez", "il": "75"},
  {"aciklama": "Çıldır", "il": "75"},
  {"aciklama": "Göle", "il": "75"},
  {"aciklama": "Hanak", "il": "75"},
  {"aciklama": "Posof", "il": "75"},
  {"aciklama": "Damal", "il": "75"},
  {"aciklama": "Aralık", "il": "76"},
  {"aciklama": "Iğdır Merkez", "il": "76"},
  {"aciklama": "Tuzluca", "il": "76"},
  {"aciklama": "Karakoyunlu", "il": "76"},
  {"aciklama": "Yalova Merkez", "il": "77"},
  {"aciklama": "Altınova", "il": "77"},
  {"aciklama": "Armutlu", "il": "77"},
  {"aciklama": "Çınarcık", "il": "77"},
  {"aciklama": "Çiftlikköy", "il": "77"},
  {"aciklama": "Termal", "il": "77"},
  {"aciklama": "Eflani", "il": "78"},
  {"aciklama": "Eskipazar", "il": "78"},
  {"aciklama": "Karabük Merkez", "il": "78"},
  {"aciklama": "Ovacık", "il": "78"},
  {"aciklama": "Safranbolu", "il": "78"},
  {"aciklama": "Yenice", "il": "78"},
  {"aciklama": "Kilis Merkez", "il": "79"},
  {"aciklama": "Elbeyli", "il": "79"},
  {"aciklama": "Musabeyli", "il": "79"},
  {"aciklama": "Polateli", "il": "79"},
  {"aciklama": "Bahçe", "il": "80"},
  {"aciklama": "Kadirli", "il": "80"},
  {"aciklama": "Osmaniye Merkez", "il": "80"},
  {"aciklama": "Düziçi", "il": "80"},
  {"aciklama": "Hasanbeyli", "il": "80"},
  {"aciklama": "Sumbas", "il": "80"},
  {"aciklama": "Toprakkale", "il": "80"},
  {"aciklama": "Akçakoca", "il": "81"},
  {"aciklama": "Düzce Merkez", "il": "81"},
  {"aciklama": "Yığılca", "il": "81"},
  {"aciklama": "Cumayeri", "il": "81"},
  {"aciklama": "Gölyaka", "il": "81"},
  {"aciklama": "Çilimli", "il": "81"},
  {"aciklama": "Gümüşova", "il": "81"},
  {"aciklama": "Kaynaşlı", "il": "81"}
];

List<String> allUniversitiesOfTurkey = [
  "Seçim Yapınız",
  "Abant İzzet Baysal Üniversitesi",
  "Abdullah Gül Üniversitesi",
  "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
  "Adana Bilim Ve Teknoloji Üniversitesi",
  "Adıyaman Üniversitesi",
  "Adnan Menderes Üniversitesi",
  "Afyon Kocatepe Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Ahi Evran Üniversitesi",
  "Akdeniz Üniversitesi",
  "Aksaray Üniversitesi",
  "Alanya Alaaddin Keykubat Üniversitesi",
  "Alanya Hamdullah Emin Paşa Üniversitesi",
  "Altınbaş Üniversitesi",
  "Amasya Üniversitesi",
  "Anadolu Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Ankara Üniversitesi",
  "Ankara Yıldırım Beyazıt Üniversitesi",
  "Antalya Akev Üniversitesi",
  "Antalya Bilim Üniversitesi",
  "Ardahan Üniversitesi",
  "Artvin Çoruh Üniversitesi",
  "Ataşehir Adıgüzel Meslek Yüksekokulu",
  "Atatürk Üniversitesi",
  "Atılım Üniversitesi",
  "Avrasya Üniversitesi",
  "Avrupa Meslek Yüksekokulu",
  "Bahçeşehir Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Bartın Üniversitesi",
  "Başkent Üniversitesi",
  "Batman Üniversitesi",
  "Bayburt Üniversitesi",
  "Beykent Üniversitesi",
  "Beykoz Üniversitesi",
  "Bezm-İ Âlem Vakıf Üniversitesi",
  "Bilecik Şeyh Edebali Üniversitesi",
  "Bingöl Üniversitesi",
  "Biruni Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Bozok Üniversitesi",
  "Bursa Teknik Üniversitesi",
  "Bülent Ecevit Üniversitesi",
  "Canik Başarı Üniversitesi",
  "Cumhuriyet Üniversitesi",
  "Çağ Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çankaya Üniversitesi",
  "Çankırı Karatekin Üniversitesi",
  "Çukurova Üniversitesi",
  "Dicle Üniversitesi",
  "Doğuş Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Dumlupınar Üniversitesi",
  "Düzce Üniversitesi",
  "Ege Üniversitesi",
  "Erciyes Üniversitesi",
  "Erzincan Üniversitesi",
  "Erzurum Teknik Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Faruk Saraç Tasarım Meslek Yüksekokulu",
  "Fatih Sultan Mehmet Vakıf Üniversitesi",
  "Fırat Üniversitesi",
  "Galatasaray Üniversitesi",
  "Gazi Üniversitesi",
  "Gaziantep Üniversitesi",
  "Gaziosmanpaşa Üniversitesi",
  "Gebze Teknik Üniversitesi",
  "Giresun Üniversitesi",
  "Gümüşhane Üniversitesi",
  "Hacettepe Üniversitesi",
  "Hakkari Üniversitesi",
  "Haliç Üniversitesi",
  "Harran Üniversitesi",
  "Hasan Kalyoncu Üniversitesi",
  "Hitit Üniversitesi",
  "Iğdır Üniversitesi",
  "Işık Üniversitesi",
  "İbn Haldun Üniversitesi",
  "İhsan Doğramacı Bilkent Üniversitesi",
  "İnönü Üniversitesi",
  "İskenderun Teknik Üniversitesi",
  "İstanbul 29 Mayıs Üniversitesi",
  "İstanbul Arel Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Ayvansaray Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "İstanbul Bilim Üniversitesi",
  "İstanbul Esenyurt Üniversitesi",
  "İstanbul Gedik Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Kavram Meslek Yüksekokulu",
  "İstanbul Kemerburgaz Üniversitesi",
  "İstanbul Kent Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Rumeli Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Şehir Üniversitesi",
  "İstanbul Şişli Meslek Yüksekokulu",
  "İstanbul Teknik Üniversitesi",
  "İstanbul Ticaret Üniversitesi",
  "İstanbul Üniversitesi",
  "İstanbul Yeni Yüzyıl Üniversitesi",
  "İstinye Üniversitesi",
  "İzmir Bakırçay Üniversitesi",
  "İzmir Demokrasi Üniversitesi",
  "İzmir Ekonomi Üniversitesi",
  "İzmir Katip Çelebi Üniversitesi",
  "İzmir Yüksek Teknoloji Enstitüsü",
  "Kadir Has Üniversitesi",
  "Kafkas Üniversitesi",
  "Kahramanmaraş Sütçü İmam Üniversitesi",
  "Kapadokya Üniversitesi",
  "Karabük Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kilis 7 Aralık Üniversitesi",
  "Kocaeli Üniversitesi",
  "Koç Üniversitesi",
  "Konya Gıda Ve Tarım Üniversitesi",
  "Kto Karatay Üniversitesi",
  "Maltepe Üniversitesi",
  "Manisa Celâl Bayar Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Marmara Üniversitesi",
  "Mef Üniversitesi",
  "Mehmet Akif Ersoy Üniversitesi",
  "Melikşah Üniversitesi",
  "Mersin Üniversitesi",
  "Mimar Sinan Güzel Sanatlar Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Munzur Üniversitesi",
  "Mustafa Kemal Üniversitesi",
  "Muş Alparslan Üniversitesi",
  "Namık Kemal Üniversitesi",
  "Necmettin Erbakan Üniversitesi",
  "Nevşehir Hacı Bektaş Veli Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Niğde Üniversitesi",
  "Nişantaşı Üniversitesi",
  "Nuh Naci Yazgan Üniversitesi",
  "Okan Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Ordu Üniversitesi",
  "Orta Doğu Teknik Üniversitesi",
  "Osmaniye Korkut Ata Üniversitesi",
  "Özyeğin Üniversitesi",
  "Pamukkale Üniversitesi",
  "Piri Reis Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sabancı Üniversitesi",
  "Sağlık Bilimleri Üniversitesi",
  "Sakarya Üniversitesi",
  "Sanko Üniversitesi",
  "Selçuk Üniversitesi",
  "Siirt Üniversitesi",
  "Sinop Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Şırnak Üniversitesi",
  "Ted Üniversitesi",
  "Tobb Ekonomi Ve Teknoloji Üniversitesi",
  "Toros Üniversitesi",
  "Trakya Üniversitesi",
  "Türk Hava Kurumu Üniversitesi",
  "Türk-Alman Üniversitesi",
  "Ufuk Üniversitesi",
  "Uludağ Üniversitesi",
  "Uşak Üniversitesi",
  "Üsküdar Üniversitesi",
  "Yalova Üniversitesi",
  "Yaşar Üniversitesi",
  "Yeditepe Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Yüksek İhtisas Üniversitesi",
  "Yüzüncü Yıl Üniversitesi",
];

List yearList = [
  "Seçim Yapınız",
  "Devam Ediyor",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
  "2017",
  "2016",
  "2015",
  "2014",
  "2013",
  "2012",
  "2011",
  "2010",
  "2009",
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
  "1999",
  "1998",
  "1997",
  "1996",
  "1995",
  "1994",
  "1993",
  "1992",
  "1991",
  "1990",
  "1989",
  "1988",
  "1987",
  "1986",
  "1985",
  "1984",
  "1983",
  "1982",
  "1981",
  "1980",
  "1979",
  "1978",
  "1977",
  "1976",
  "1975",
  "1974",
  "1973",
  "1972",
  "1971",
  "1970",
  "1969",
  "1968",
  "1967",
  "1966",
  "1965",
  "1964",
  "1963",
  "1962",
  "1961",
  "1960",
  "1959",
  "1958",
  "1957",
  "1956",
  "1955",
  "1954",
  "1953",
  "1952",
  "1951",
  "1950",
  "1949",
  "1948",
  "1947",
  "1946",
  "1945",
  "1944",
  "1943",
  "1942",
  "1941",
  "1940",
  "1939",
  "1938",
  "1937",
  "1936",
  "1935",
  "1934",
  "1933",
  "1932",
  "1931",
  "1930",
  "1929",
  "1928",
  "1927",
  "1926",
  "1925",
  "1924",
  "1923",
  "1922",
  "1921",
];

List allDegrees = ["Seçim Yapınız", "Ön Lisans", "Lisans", "Yüksek Lisans", "Doktora"];

List allDepartments = [
  "Seçim Yapınız",
  "Acil Yardım Ve Afet Yönetimi",
  "Adli Bilişim Mühendisliği",
  "Aile Ekonomisi Ve Beslenme Öğretmenliği",
  "Aile Ve Tüketici Bilimleri",
  "Aile Ve Tüketici Bilimleri Öğretmenliği",
  "Aksesuar Tasarımı",
  "Aktüerya",
  "Aktüerya Bilimleri",
  "Aktüerya Ve Risk Yönetimi",
  "Alman Dili Ve Edebiyatı",
  "Almanca Öğretmenliği",
  "Amerikan Kültürü Ve Edebiyatı",
  "Animasyon",
  "Antrenörlük Eğitimi",
  "Antropoloji",
  "Arap Dili Ve Edebiyatı",
  "Arapça Öğretmenliği",
  "Arkeoloji",
  "Arkeoloji Ve Sanat Tarihi",
  "Arnavut Dili Ve Edebiyatı",
  "Arp",
  "Astronomi Ve Uzay Bilimleri",
  "Avrupa Birliği İlişkileri",
  "Azerbaycan Türkçesi Ve Edebiyatı",
  "Ağaç İşleri Endüstri Mühendisliği",
  "Bahçe Bitkileri",
  "Bale",
  "Bale Dansçılığı",
  "Balıkçılık Teknolojisi",
  "Balıkçılık Teknolojisi Mühendisliği",
  "Bando Şefliği",
  "Bankacılık",
  "Bankacılık Ve Finans",
  "Bankacılık Ve Sigortacılık",
  "Baskı Sanatları",
  "Basım Teknolojileri",
  "Basın Ve Yayın",
  "Beden Eğitimi Ve Spor Öğretmenliği",
  "Besin Teknolojisi",
  "Beslenme Ve Diyetetik",
  "Bileşik Sanatlar",
  "Bilgi Ve Belge Yönetimi",
  "Bilgisayar Bilimi Ve Mühendisliği",
  "Bilgisayar Bilimleri",
  "Bilgisayar Mühendisliği",
  "Bilgisayar Sistemleri Öğretmenliği",
  "Bilgisayar Teknolojisi Ve Bilişim Sistemleri",
  "Bilgisayar Ve Kontrol Öğretmenliği",
  "Bilgisayar Ve Yazılım Mühendisliği",
  "Bilgisayar Ve Öğretim Teknolojileri Öğretmenliği",
  "Bilgisayar Öğretmenliği",
  "Bilim Tarihi",
  "Bilişim Sistemleri Mühendisliği",
  "Bilişim Sistemleri Ve Teknolojileri",
  "Bitki Koruma",
  "Bitkisel Üretim",
  "Bitkisel Üretim Ve Teknolojileri",
  "Biyoenformatik Ve Genetik",
  "Biyokimya",
  "Biyoloji",
  "Biyoloji Öğretmenliği",
  "Biyomedikal Mühendisliği",
  "Biyomühendislik",
  "Biyosistem Mühendisliği",
  "Biyoteknoloji",
  "Biyoteknoloji Ve Moleküler Biyoloji",
  "Boşnak Dili Ve Edebiyatı",
  "Bulgar Dili Ve Edebiyatı",
  "Büro Yönetimi Öğretmenliği",
  "Cam",
  "Canlandırma Filmi Tasarım Ve Yönetimi",
  "Caz",
  "Cevher Hazırlama Mühendisliği",
  "Coğrafya",
  "Coğrafya Öğretmenliği",
  "Dans",
  "Dekoratif Sanatlar Öğretmenliği",
  "Deniz Teknolojisi Mühendisliği",
  "Deniz Ulaştırma İşletme Mühendisliği",
  "Denizcilik İşletmeleri Yönetimi",
  "Deri Mühendisliği",
  "Dil Ve Konuşma Terapisi",
  "Dilbilim",
  "Din Kültürü Ve Ahlak Bilgisi Öğretmenliği",
  "Diş Hekimliği",
  "Drama Ve Oyunculuk",
  "Dramatik Yazarlık",
  "Dramatik Yazarlık-Dramaturji",
  "Duysal (Ses) Sanatları Tasarımı",
  "Döküm Öğretmenliği",
  "Dünya Dinleri",
  "Ebelik",
  "Eczacılık",
  "Ekonometri",
  "Ekonomi",
  "Ekonomi Politik Ve Toplum Felsefesi",
  "Ekonomi Ve Finans",
  "El Sanatları",
  "El Sanatları Tasarımı Ve Üretimi",
  "Elektrik Mühendisliği",
  "Elektrik Ve Elektronik Mühendisliği",
  "Elektrik Öğretmenliği",
  "Elektronik Mühendisliği",
  "Elektronik Ve Bilgisayar Öğretmenliği",
  "Elektronik Ve Haberleşme Mühendisliği",
  "Elektronik Ve Haberleşme Öğretmenliği",
  "Elektronik Öğretmenliği",
  "Endüstri Mühendisliği",
  "Endüstri Sistemleri Mühendisliği",
  "Endüstri Tasarımı",
  "Endüstri Ve Sistem Mühendisliği",
  "Endüstri Ürünleri Tasarımı",
  "Endüstriyel Tasarım",
  "Endüstriyel Tasarım Mühendisliği",
  "Endüstriyel Teknoloji Öğretmenliği",
  "Enerji Sistemleri Mühendisliği",
  "Enerji Öğretmenliği",
  "Enformasyon Teknolojileri",
  "Engellilerde Beden Eğitimi Ve Spor Öğretmenliği",
  "Ergoterapi",
  "Ermeni Dili Ve Edebiyatı",
  "Eski Yunan Dili Ve Edebiyatı",
  "Eski Çini Onarımları",
  "Etnoloji",
  "Ev Ekonomisi",
  "Fagot",
  "Fars Dili Ve Edebiyatı",
  "Felsefe",
  "Felsefe Grubu Öğretmenliği",
  "Fen Bilgisi Öğretmenliği",
  "Film Tasarım Ve Yazarlık",
  "Film Tasarım Ve Yönetmenliği",
  "Film Tasarımı",
  "Finans Matematiği",
  "Finansal Ekonometri",
  "Fizik",
  "Fizik Mühendisliği",
  "Fizik Tedavi Ve Rehabilitasyon",
  "Fizik Öğretmenliği",
  "Flüt",
  "Fotoğraf",
  "Fotoğraf Ve Grafik Sanatlar",
  "Fotoğraf Ve Video",
  "Fransız Dili Ve Edebiyatı",
  "Fransızca Öğretmenliği",
  "Gastronomi",
  "Gastronomi Ve Mutfak Sanatları",
  "Gayrimenkul Ve Varlık Değerleme",
  "Gazetecilik",
  "Geleneksel Türk El Sanatları",
  "Geleneksel Türk Müzikleri",
  "Geleneksel Türk Sanatları",
  "Gemi Makineleri İşletme Mühendisliği",
  "Gemi Ve Deniz Teknolojisi Mühendisliği",
  "Gemi Ve Yat Tasarımı",
  "Gemi İnşa Ve Gemi Makineleri Mühendisliği",
  "Gemi İnşaatı Mühendisliği",
  "Gemi İnşaatı Ve Gemi Makineleri Mühendisliği",
  "Genel Müzikoloji",
  "Genetik Ve Biyoinformatik",
  "Genetik Ve Biyomühendislik",
  "Geomatik Mühendisliği",
  "Gerontoloj",
  "Girişimcilik",
  "Gitar",
  "Giyim Endüstrisi Öğretmenliği",
  "Giyim Öğretmenliği",
  "Grafik",
  "Grafik Resimleme Ve Baskı",
  "Grafik Sanatları",
  "Grafik Tasarım",
  "Grafik Öğretmenliği",
  "Görme Engelliler Öğretmenliği",
  "Görsel Sanatlar",
  "Görsel Sanatlar Ve Görsel İletişim Tasarımı",
  "Görsel İletişim",
  "Görsel İletişim Tasarımı",
  "Görüntü Sanatları",
  "Gümrük İşletme",
  "Gürcü Dili Ve Edebiyatı",
  "Gıda Mühendisliği",
  "Gıda Teknolojisi",
  "Halkbilim",
  "Halkla İlişkiler",
  "Halkla İlişkiler Ve Reklamcılık",
  "Halkla İlişkiler Ve Tanıtım",
  "Halı Kilim",
  "Halı, Kilim Ve Eski Kumaş Desenleri",
  "Harita Mühendisliği",
  "Hat",
  "Hava Trafik Kontrol",
  "Havacılık Elektrik Ve Elektroniği",
  "Havacılık Ve Uzay Mühendisliği",
  "Havacılık Yönetimi",
  "Havacılık İşletmeciliği",
  "Hayvansal Üretim",
  "Hazır Giyim Öğretmenliği",
  "Hemşirelik",
  "Hemşirelik Ve Sağlık Hizmetleri",
  "Heykel",
  "Hidrojeoloji Mühendisliği",
  "Hindoloji",
  "Hititoloji",
  "Hukuk",
  "Hungaroloji",
  "Hırvat Dili Ve Edebiyatı",
  "Japon Dili Ve Edebiyatı",
  "Japonca Öğretmenliği",
  "Jeodezi Ve Fotogrametri Mühendisliği",
  "Jeofizik Mühendisliği",
  "Jeoloji Mühendisliği",
  "Kalıpçılık Öğretmenliği",
  "Kamu Yönetimi",
  "Karşılaştırmalı Edebiyat",
  "Karşılaştırmalı Edebiyat (İngilizce)",
  "Keman",
  "Kentsel Tasarım Ve Peyzaj Mimarisi",
  "Kimya",
  "Kimya Mühendisliği",
  "Kimya Mühendisliği Ve Uygulamalı Kimya",
  "Kimya Ve Süreç Mühendisliği",
  "Kimya Öğretmenliği",
  "Kimya-Biyoloji Mühendisliği",
  "Klarnet",
  "Klasik Arkeoloji",
  "Klasik Bale",
  "Kompozisyon",
  "Kompozisyon Ve Orkestra Şefliği",
  "Kompozisyon(Bestecilik)",
  "Konaklama İşletmeciliği",
  "Konaklama İşletmeciliği Eğitimi",
  "Konaklama İşletmeciliği Öğretmenliği",
  "Kontrabas",
  "Kontrol Mühendisliği",
  "Kontrol Ve Otomasyon Mühendisliği",
  "Kontrol Öğretmenliği",
  "Kore Dili Ve Edebiyatı",
  "Koreoloji",
  "Korno",
  "Koro",
  "Kuaförlük Ve Güzellik Bilgisi Öğretmenliği",
  "Kurgu-Ses Ve Görüntü Yönetimi",
  "Kuyumculuk",
  "Kuyumculuk Ve Mücevher Tasarımı",
  "Kültür Varlıklarını Koruma Ve Onarım",
  "Kültür Yönetimi",
  "Kültürel Çalışmalar",
  "Küresel Siyaset Ve Uluslararası İlişkiler",
  "Küresel Ve Uluslararası İlişkiler",
  "Kürt Dili Ve Edebiyatı",
  "Kütüphanecilik",
  "Latin Dili Ve Edebiyatı",
  "Leh Dili Ve Edebiyatı",
  "Lojistik",
  "Lojistik Yönetimi",
  "Maden Mühendisliği",
  "Makine Mühendisliği",
  "Makine Resim Ve Konstrüksiyonu Öğretmenliği",
  "Makine Ve İmalat Mühendisliği",
  "Maliye",
  "Malzeme Bilimi Ve Mühendisliği",
  "Malzeme Bilimi Ve Nano Mühendislik",
  "Malzeme Bilimi Ve Nanoteknoloji Mühendisliği",
  "Malzeme Mühendisliği",
  "Matbaa Öğretmenliği",
  "Matematik",
  "Matematik Mühendisliği",
  "Matematik Ve Bilgisayar Bilimleri",
  "Matematik Öğretmenliği",
  "Matematik-Bilgisayar",
  "Medya Ve Görsel Sanatlar",
  "Medya Ve İletişim",
  "Medya Ve İletişim Sistemleri",
  "Mekatronik Mühendisliği",
  "Mekatronik Sistemler Mühendisliği",
  "Mekatronik Öğretmenliği",
  "Mesleki Resim Öğretmenliği",
  "Metal Öğretmenliği",
  "Metalurji Ve Malzeme Mühendisliği",
  "Meteoroloji Mühendisliği",
  "Mimarlık",
  "Mobilya Ve Dekorasyon Öğretmenliği",
  "Moda Giyim Tasarımı",
  "Moda Tasarımı",
  "Moda Tasarımı Öğretmenliği",
  "Moda Ve Tekstil Tasarımı",
  "Moda Ve Tekstil Tasarımı",
  "Modern Dans",
  "Moleküler Biyoloji Ve Genetik",
  "Moleküler Biyoloji, Genetik Ve Biyomühendislik",
  "Muhasebe",
  "Muhasebe Bilgi Sistemleri",
  "Muhasebe Ve Denetim",
  "Muhasebe Ve Finansal Yönetim",
  "Muhasebe Ve Finansman Öğretmenliği",
  "Mutfak Sanatları Ve Yönetimi",
  "Mütercim-Tercümanlık (Almanca)",
  "Mütercim-Tercümanlık (Arapça)",
  "Mütercim-Tercümanlık (Bulgarca)",
  "Mütercim-Tercümanlık (Farsça)",
  "Mütercim-Tercümanlık (Fransızca)",
  "Mütercim-Tercümanlık (Fransızca)",
  "Mütercim-Tercümanlık (Rusça)",
  "Mütercim-Tercümanlık (Türkçe-Almanca-İngilizce)",
  "Mütercim-Tercümanlık (Türkçe-İngilizce-Fransızca)",
  "Mütercim-Tercümanlık (Çift Dilli: İngilizce-Almanca)",
  "Mütercim-Tercümanlık (Çift Dilli: İngilizce-Fransızca)",
  "Mütercim-Tercümanlık (Çince)",
  "Mütercim-Tercümanlık (İngilizce)",
  "Müzik",
  "Müzik Bilimleri",
  "Müzik Teknolosi",
  "Müzik Teorisi",
  "Müzik Toplulukları",
  "Müzik Öğretmenliği",
  "Müzikoloji",
  "Nakış Öğretmenliği",
  "Nefesli Çalgılar Ve Vurmalı Çalgılar",
  "Nükleer Enerji Mühendisliği",
  "Obua",
  "Odyoloji",
  "Okul Öncesi Öğretmenliği",
  "Opera",
  "Opera Ve Konser Şarkıcılığı",
  "Opera Şarkıcılığı",
  "Optik Ve Akustik Mühendisliği",
  "Organik Tarım İşletmeciliği",
  "Orman Endüstrisi Mühendisliği",
  "Orman Mühendisliği",
  "Ortez-Protez",
  "Osmanlı Dönemi Karşılaştırmalı Müzik",
  "Otel Yöneticiliği",
  "Otomotiv Mühendisliği",
  "Otomotiv Öğretmenliği",
  "Oyunculuk",
  "Pazarlama",
  "Pazarlama Öğretmenliği",
  "Performans",
  "Perfüzyon",
  "Petrol Ve Doğalgaz Mühendisliği",
  "Peyzaj Mimarlığı",
  "Pilot Eğitimi",
  "Pilotaj",
  "Piyano",
  "Piyano Onarımı Yapımı",
  "Piyano-Arp-Gitar",
  "Plastik Sanatlar",
  "Plastik Sanatlar Ve Resim",
  "Polimer Mühendisliği",
  "Polonya Dili Ve Kültürü (Lehçe)",
  "Popüler Müzik Şarkıcılığı",
  "Prehistorya",
  "Protohistorya Ve Ön Asya Arkeolojisi",
  "Psikoloji",
  "Radyo Ve Televizyon",
  "Radyo, Televizyon Ve Sinema",
  "Raylı Sistemler Mühendisliği",
  "Rehberlik Ve Psikolojik Danışmanlık",
  "Reklam Tasarımı Ve İletişimi",
  "Reklamcılık",
  "Rekreasyon",
  "Rekreasyon Yönetimi",
  "Resim",
  "Resim-Baskı Sanatları",
  "Resim-İş Eğitimi",
  "Resim-İş Öğretmenliği",
  "Rus Dili Ve Edebiyatı",
  "Sahne Dekorları Ve Kostümü",
  "Sahne Sanatları",
  "Sahne Tasarımı",
  "Sahne Ve Gösteri Sanatları Yönetimi",
  "Sanat (Tasarım) Yönetimi",
  "Sanat Eserleri Konservasyonu Ve Restorasyonu",
  "Sanat Tarihi",
  "Sanat Tasarımı",
  "Sanat Ve Kültür Yönetimi",
  "Sanat Ve Tasarım",
  "Sanat Yönetimi",
  "Sağlık Eğitimi",
  "Sağlık Kurumları Yöneticiliği",
  "Sağlık Kurumları Yönetimi",
  "Sağlık Kurumları İşletmeciliği",
  "Sağlık Memurluğu",
  "Sağlık Yönetimi",
  "Sağlık İdaresi",
  "Seramik",
  "Seramik Sanatları",
  "Seramik Ve Cam",
  "Seramik Ve Cam Tasarımı",
  "Seramik Öğretmenliği",
  "Sermaye Piyasaları Ve Portföy Yönetimi",
  "Sermaye Piyasası",
  "Sermaye Piyasası Denetim Ve Derecelendirme",
  "Ses Eğitimi",
  "Seyahat İşletmeciliği",
  "Seyahat İşletmeciliği Ve Turizm Rehberliği",
  "Seyahat İşletmeciliği Ve Turizm Rehberliği Eğitimi",
  "Seyahat İşletmeciliği Ve Turizm Rehberliği Öğretmenliği",
  "Sigortacılık",
  "Sigortacılık Ve Risk Yönetimi",
  "Sigortacılık Ve Sosyal Güvenlik",
  "Sinema Ve Dijital Medya",
  "Sinema Ve Televizyon",
  "Sinoloji",
  "Sistem Mühendisliği",
  "Sivil Hava Ulaştırma İşletmeciliği",
  "Sivil Havacılık İşletmeciliği",
  "Siyaset Bilimi",
  "Siyaset Bilimi Ve Kamu Yönetimi",
  "Siyaset Bilimi Ve Uluslararası İlişkiler",
  "Sosyal Antropoloji",
  "Sosyal Bilgiler Öğretmenliği",
  "Sosyal Hizmetler",
  "Sosyoloji",
  "Spor Bilimleri",
  "Spor Yöneticiliği",
  "Su Bilimleri Ve Mühendisliği",
  "Su Ürünleri",
  "Su Ürünleri Mühendisliği ",
  "Sümeroloji",
  "Süt Teknolojisi",
  "Sınıf Öğretmenliği",
  "Takı Tasarımı",
  "Takı Teknolojisi Ve Tasarımı",
  "Talaşlı Üretim Öğretmenliği",
  "Tapu Kadastro",
  "Tarih",
  "Tarih Öncesi Arkeolojisi",
  "Tarih Öğretmenliği",
  "Tarla Bitkileri",
  "Tarım Ekonomisi",
  "Tarım Makineleri",
  "Tarım Teknolojisi",
  "Tarımsal Biyoteknoloji",
  "Tarımsal Genetik Mühendisliği",
  "Tarımsal Yapılar Ve Sulama",
  "Tasarım Ve Konstrüksiyon Öğretmenliği",
  "Taşınabilir Kültür Varlıklarını Koruma Ve Onarım",
  "Teknoloji Ve Bilgi Yönetimi",
  "Tekstil",
  "Tekstil Dokuma Ve Örgü Öğretmenliği",
  "Tekstil Geliştirme Ve Pazarlama",
  "Tekstil Mühendisliği",
  "Tekstil Tasarım",
  "Tekstil Tasarımı Ve Üretimi",
  "Tekstil Terbiye Öğretmenliği",
  "Tekstil Ve Deri Moda Tasarımı",
  "Tekstil Ve Moda Tasarımı",
  "Tekstil Öğretmenliği",
  "Telekomünikasyon Mühendisliği",
  "Telekomünikasyon Öğretmenliği",
  "Televizyon Haberciliği Ve Programcılığı",
  "Temel Bilimler",
  "Teori",
  "Tesisat Öğretmenliği",
  "Tezhip",
  "Tiyatro",
  "Tiyatro Eleştirmenliği Ve Dramaturji",
  "Toplumsal Ve Siyasal Bilimler",
  "Toprak",
  "Toprak Bilimi Ve Bitki Besleme",
  "Trombon",
  "Trompet",
  "Tuba",
  "Turizm Animasyonu",
  "Turizm Rehberliği",
  "Turizm Ve Otel İşletmeciliği",
  "Turizm Ve Otelcilik",
  "Turizm İşletmeciliği",
  "Turizm İşletmeciliği Ve Otelcilik",
  "Türk Dili Ve Edebiyatı",
  "Türk Dili Ve Edebiyatı Öğretmenliği",
  "Türk Din Musikisi",
  "Türk Halk Müziği",
  "Türk Halk Müziği Ses Eğitimi",
  "Türk Halk Müziği Çalgı Eğitimi",
  "Türk Halk Oyunları",
  "Türk Halkbilimi",
  "Türk Musikisi",
  "Türk Musikisi Temel Bilimler",
  "Türk Müziği",
  "Türk Sanat Müziği",
  "Türk Sanat Müziği Ses Eğitimi",
  "Türk Sanat Müziği Temel Bilimler",
  "Türkçe Öğretmenliği",
  "Türkçe Öğretmenliği Öğretim",
  "Tütün Eksperliği Yüksekokulu",
  "Tıp",
  "Tıp Mühendisliği",
  "Ulaştırma Mühendisliği",
  "Ulaştırma Ve Lojistik",
  "Uluslararası Finans",
  "Uluslararası Finans Ve Bankacılık",
  "Uluslararası Girişimcilik",
  "Uluslararası Lojistik",
  "Uluslararası Lojistik Ve Taşımacılık",
  "Uluslararası Lojistik Yönetimi",
  "Uluslararası Ticaret",
  "Uluslararası Ticaret Ve Finans",
  "Uluslararası Ticaret Ve Finansman",
  "Uluslararası Ticaret Ve Lojistik",
  "Uluslararası Ticaret Ve Lojistik Yönetimi",
  "Uluslararası Ticaret Ve Pazarlama",
  "Uluslararası Ticaret Ve İşletmecilik",
  "Uluslararası Ticaret, Lojistik Ve İşletmecilik",
  "Uluslararası Çalışmalar",
  "Uluslararası İlahiyat",
  "Uluslararası İlişkiler",
  "Uluslararası İlişkiler Ve Avrupa Birliği",
  "Uluslararası İlişkiler Ve Deniz Güvenliği",
  "Uluslararası İşletme Yönetimi",
  "Uluslararası İşletmecilik",
  "Urdu Dili Ve Edebiyatı",
  "Uzay Bilimleri Ve Teknolojileri",
  "Uzay Mühendisliği",
  "Uçak Elektrik-Elektronik",
  "Uçak Gövde-Motor",
  "Uçak Gövde-Motor Bakımı",
  "Uçak Mühendisliği",
  "Veterinerlik",
  "Viyola",
  "Viyolonsel",
  "Vurmalı Çalgılar",
  "Yaban Hayatı Ekolojisi Ve Yönetimi",
  "Yapı Ressamlığı Öğretmenliği",
  "Yapı Tasarımı Öğretmenliği",
  "Yapı Öğretmenliği",
  "Yaygın Din Öğretimi Ve Uygulamaları",
  "Yaylı Çalgılar",
  "Yaylı Çalgılar Yapımı",
  "Yazılım Mühendisliği",
  "Yeni Medya",
  "Yeni Medya Ve Gazetecilik",
  "Yiyecek Ve İçecek İşletmeciliği",
  "Yunan Dili Ve Edebiyatı",
  "Yönetim Bilimleri",
  "Yönetim Bilimleri (İşletme Fakültesi)",
  "Yönetim Bilimleri Programları",
  "Yönetim Bilişim Sistemleri",
  "Zaza Dili Ve Edebiyatı",
  "Zeotekni",
  "Zihin Engelliler Öğretmenliği",
  "Ziraat Mühendisliği",
  "Zootekni",
  "Çalgı",
  "Çalgı Eğitimi",
  "Çalgı Yapım",
  "Çalışma Ekonomisi Ve Endüstri İlişkileri",
  "Çağdaş Türk Lehçeleri Ve Edebiyatları",
  "Çağdaş Yunan Dili Ve Edebiyatı",
  "Çerkez Dili Ve Edebiyatı",
  "Çeviribilim (Almanca)",
  "Çeviribilim (İngilizce)",
  "Çevre Mühendisliği",
  "Çin Dili Ve Edebiyatı",
  "Çini",
  "Çini Tasarımı",
  "Çizgi Film Ve Animasyon",
  "Çiçek, Örgü Ve Dokuma Öğretmenliği",
  "Çocuk Gelişimi",
  "Çocuk Gelişimi Ve Okul Öncesi Öğretmenliği",
  "Çocuk Sağlığı Ve Gelişimi Rehberlik (Pdr)",
  "Özel Eğitim Öğretmenliği",
  "Üflemeli Ve Vurmalı Çalgılar",
  "Üretim Sistemleri Mühendisliği",
  "Üstün Zekâlılar Öğretmenliği",
  "İbrani Dili Ve Edebiyatı",
  "İktisat",
  "İlahiyat",
  "İletişim",
  "İletişim Bilimleri",
  "İletişim Sanatları",
  "İletişim Tasarımı Ve Yönetimi",
  "İletişim Ve Tasarım",
  "İlköğretim Din Kültürü Ve Ahlak Bilgisi Öğretmenliği",
  "İlköğretim Matematik Öğretmenliği",
  "İmalat Mühendisliği",
  "İngiliz Dil Bilimi",
  "İngiliz Dili Ve Edebiyatı",
  "İngiliz Dili Ve Karşılaştırmalı Edebiyat",
  "İngilizce Öğretmenliği",
  "İngilizce Öğretmenliği Öğretimi",
  "İnsan Kaynakları Yönetimi",
  "İnsan Ve Toplum Bilimleri",
  "İnşaat Mühendisliği",
  "İslam Ve Din Bilimleri",
  "İslami İlimler",
  "İspanyol Dili Ve Edebiyatı",
  "İstatistik",
  "İstatistik Ve Bilgisayar Bilimleri",
  "İtalyan Dili Ve Edebiyatı",
  "İç Mimarlık",
  "İç Mimarlık Ve Çevre Tasarımı",
  "İş Sağlığı Ve Güvenliği",
  "İşitme Engelliler Öğretmenliği",
  "İşletme",
  "İşletme Bilgi Yönetimi",
  "İşletme Enformatiği",
  "İşletme Mühendisliği",
  "İşletme Yönetimi",
  "İşletme Öğretmenliği",
  "İşletme-Ekonomi",
  "Şan",
  "Şehir Ve Bölge Planlama"
];

List saatList = [
  "07.00",
  "08.00",
  "09.00",
  "10.00",
  "11.00",
  "12.00",
  "13.00",
  "14.00",
  "15.00",
  "16.00",
  "17.00",
  "18.00",
  "19.00",
  "20.00",
  "21.00",
  "22.00",
  "23.00",
  "00.00"
];

List haftaninGunleri = ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"];

String checkPrms(Map<String, dynamic> map, String deger) {
  try {
    if (map.containsKey(deger)) {
      return map[deger].toString();
    } else {
      return "";
    }
  } catch (e) {
    print("map:" + map.toString());
    print("deger:" + deger.toString());
  }
}
