import 'package:flutter/material.dart';

//const kBackgroundColor = Color(0xFFF8F8F8);
//const kActiveIconColor = Color(0xFFE68342);
//const kTextColor = Color(0xFF222B45);
//const kBlueLightColor = Color(0xFFC7B8F5);
//const kBlueColor = Color(0xFF817DC0);
const kShadowColor = Color(0xFFE6E6E6);
const turuncuDefault = Color.fromRGBO(250, 151, 93, 1);
const pictureBgColor = Color.fromRGBO(48, 45, 44, 1);
const defaultLink = Color.fromRGBO(21, 141, 204, 1);
const sariDefault = Color.fromRGBO(253, 196, 37, 1);
final golgeDefault = Color(0xFFD3D3D3).withOpacity(.84);
const linkColor = Color(0xFF3BB3BD);
const cupertionDefault = Color.fromARGB(255, 0, 122, 255);

const topViewColor = Color(0xFFF5CEB8);
const widgetBackgroundColor = Color.fromRGBO(240, 240, 240, 1);
const textDisabledColor = Color.fromRGBO(126, 126, 126, 1);
const turkuazRenk = Color.fromRGBO(65, 202, 198, 1);
final kBoxShadowColor = Color(0xFFD3D3D3).withOpacity(.84);
const profilRenk = Color.fromRGBO(158, 146, 134, 1);

const yesilDefault = Color.fromRGBO(116, 184, 22, 1);
const yesil1 = Color.fromRGBO(192, 235, 117, 1);
const yesil2 = Color.fromRGBO(148, 216, 45, 1);
const yesil3 = Color.fromRGBO(130, 201, 30, 1);
const yesil4 = Color.fromRGBO(116, 184, 22, 1);
const yesil5 = Color.fromRGBO(102, 168, 15, 1);
const yesil6 = Color.fromRGBO(92, 148, 13, 1);

const turkuazDefault = Color.fromRGBO(65, 202, 198, 1);
const turkuazWithOpacity = Color.fromRGBO(65, 202, 198, 0.8);
const turkuazWithOpacity2 = Color.fromRGBO(65, 202, 198, 0.6);
const turkuazWithOpacity3 = Color.fromRGBO(65, 202, 198, 0.4);
const turkuazWithOpacity4 = Color.fromRGBO(65, 202, 198, 0.2);

const morDefault = Color.fromRGBO(82, 67, 101, 1);

const MaterialColor turkuazMaterialColor = const MaterialColor(
  0xFF41CAC6,
  const <int, Color>{
    50: Color.fromRGBO(65, 202, 198, .1),
    100: Color.fromRGBO(65, 202, 198, .2),
    200: Color.fromRGBO(65, 202, 198, .3),
    300: Color.fromRGBO(65, 202, 198, .4),
    400: Color.fromRGBO(65, 202, 198, .5),
    500: Color.fromRGBO(65, 202, 198, .6),
    600: Color.fromRGBO(65, 202, 198, .7),
    700: Color.fromRGBO(65, 202, 198, .8),
    800: Color.fromRGBO(65, 202, 198, .9),
    900: Color.fromRGBO(65, 202, 198, 1),
  },
);

const MaterialColor morMaterialColor = const MaterialColor(
  0xFF524365,
  const <int, Color>{
    50: Color.fromRGBO(82, 67, 101, .1),
    100: Color.fromRGBO(82, 67, 101, .2),
    200: Color.fromRGBO(82, 67, 101, .3),
    300: Color.fromRGBO(82, 67, 101, .4),
    400: Color.fromRGBO(82, 67, 101, .5),
    500: Color.fromRGBO(82, 67, 101, .6),
    600: Color.fromRGBO(82, 67, 101, .7),
    700: Color.fromRGBO(82, 67, 101, .8),
    800: Color.fromRGBO(82, 67, 101, .9),
    900: Color.fromRGBO(82, 67, 101, 1),
  },
);

const defaultTurkuazGradient =
    const LinearGradient(begin: Alignment.topCenter, colors: [
  Color.fromRGBO(65, 202, 198, 1),
  Color.fromRGBO(65, 202, 198, 0.8),
  Color.fromRGBO(65, 202, 198, 0.6),
]);

/// Construct a color from a hex code string, of the format #RRGGBB.
Color hexToColor(String code) {
  return new Color(int.parse(code.substring(1, 7), radix: 16) + 0xFF000000);
}

// Bütün kategoriler
List<String> allCategories = [
  "3D Max",
  "ACT",
  "ALES",
  "ALS",
  "ALÜGS",
  "ASP",
  "ASP.NET Core",
  "ASP.NET MVC",
  "ASP.NET Web API",
  "ASP.NET Web Forms",
  "ATPL",
  "AYT",
  "Abaqus",
  "Adalet Bakanlığı Sınavları",
  "Adli Yargı",
  "Adobe After Effects",
  "Adobe Dreamweaver",
  "Adobe Flash",
  "Adobe FreeHand",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Premiere",
  "Advanced Placement - Bilgisayar Bilimleri",
  "Advanced Placement - Biyoloji",
  "Advanced Placement - Fizik",
  "Advanced Placement - Kimya",
  "Advanced Placement - Makroekonomi",
  "Advanced Placement - Matematik",
  "Advanced Placement - Mikroekonomi",
  "Advanced Placement - Müzik Teorisi",
  "Advanced Placement - Psikoloji",
  "Advanced Placement - Sanat Tarihi",
  "Advanced Placement - Çevre Bilimleri",
  "Advanced Placement - İngiliz Edebiyatı",
  "Advanced Placement - İstatistik",
  "Afrika Dili",
  "Aile Birleşim Sınavı",
  "Akordiyon",
  "Akıl Oyunları",
  "Almanca",
  "Amigurumi",
  "Anatomi",
  "Android",
  "AngularJS",
  "Animasyon",
  "Ansys APDL",
  "Ansys Workbench",
  "Arapça",
  "Araştırma Teknikleri",
  "ArcGIS",
  "Arduino",
  "Armoni",
  "Arnavutça",
  "Astroloji",
  "Astronomi",
  "Atıcılık",
  "AutoCAD",
  "AutoCAD Civil 3D",
  "AutoCAD Plant 3D",
  "AutoForm",
  "Autodesk Advance Steel",
  "Autodesk Fusion 360",
  "Autodesk Inventor",
  "Autodesk Navisworks",
  "Autodesk Revit",
  "Autodesk Robot Structural Analysis",
  "Azerice",
  "BULATS",
  "Badminton",
  "Bale",
  "Bariton",
  "Bas",
  "Basketbol",
  "Baskça",
  "Bateri",
  "Batı Dilleri ve Edebiyatı",
  "Bağlama",
  "Bchata",
  "Belarusça",
  "Bengalce",
  "Biharca",
  "Bilardo",
  "Bilek Güreşi",
  "Bilgi Teknolojisi",
  "Bilgisayar",
  "Bilgisayar Müh.",
  "Bilgisayarlı Muhasebe",
  "Bilişim Sistemleri",
  "Binicilik",
  "Bisiklet",
  "Biyofizik",
  "Biyokimya",
  "Biyoloji",
  "Biyomedikal Müh.",
  "Blender",
  "Boks",
  "Bolero",
  "Bongo",
  "Borazan",
  "Borsa",
  "Bowling",
  "Boşnakça",
  "Break Dans",
  "Bretonca",
  "Briç",
  "Bulgarca",
  "Buzuki",
  "BÜEPT",
  "BİLET",
  "C",
  "C#",
  "C++",
  "CAD",
  "CAEL",
  "CEH",
  "CFA",
  "CFE",
  "CISA",
  "CISM",
  "CISSP",
  "CMA",
  "CNC",
  "CPA",
  "CPL",
  "CRM",
  "Cam İşleme",
  "Cambridge English - Advanced (CAE)",
  "Cambridge English - Business (BEC)",
  "Cambridge English - First (FCE)",
  "Cambridge English - Key (KET)",
  "Cambridge English - Preliminary (PET)",
  "Cambridge English - Proficiency (CPE)",
  "Cambridge English - YLE Flyers",
  "Cambridge English - YLE Movers",
  "Cambridge English - YLE Starters",
  "Catia",
  "Cha Cha",
  "Clips",
  "Cobol",
  "CorelDraw",
  "Coğrafya",
  "Cümbüş",
  "DALF",
  "DELF",
  "DGS",
  "DILF",
  "DLR",
  "DUS",
  "Dalış",
  "Dama",
  "Danca",
  "Darbuka",
  "Davul",
  "Denetim - Bilgi Teknolojileri",
  "Denetim - Finansal Denetim",
  "Denetim - Vergi Denetimi",
  "Denetim - İç Denetim",
  "Deprem Müh.",
  "Derin Öğrenme",
  "DiaLux",
  "Dikiş Nakış Terzilik",
  "Diksiyon ve Hitabet",
  "Dil ve Anlatım",
  "Dil ve Konuşma Bozuklukları",
  "Din Kültürü ve Ahlak Bilgisi",
  "Diş Hekimliği",
  "Donanım",
  "Down Sendromu",
  "Doğal Dil İşleme",
  "Drama",
  "Dövme Yapımı",
  "DİB-MBSTS",
  "EKPSS",
  "EKYS",
  "ESOL",
  "Editörlük",
  "Ekonometri",
  "Ekonomi",
  "Elektrik Müh.",
  "Elektronik Müh.",
  "Endonezya Dili",
  "Endüstri Müh.",
  "Endüstri Ürünleri Tasarımı",
  "Eritre Dili",
  "Ermenice",
  "Esperantoca",
  "Estonyaca",
  "Etabs",
  "Farmakoloji",
  "Farsça",
  "Felsefe",
  "Fen Bilgisi",
  "Fen Bilimleri",
  "Filipince",
  "Film ve Sinema",
  "Finans",
  "Fince",
  "Fizik",
  "Fizik Müh.",
  "Fiziksel Engelliler",
  "Flemenkçe",
  "Flüt",
  "Fotoğrafcılık",
  "Foxtrot",
  "Fransız Edebiyatı",
  "Fransızca",
  "Futbol",
  "GMAT",
  "GRE",
  "GYS",
  "Galce",
  "Galiçyaca",
  "Gemi Müh.",
  "Genetik",
  "Geometri",
  "Girişimcilik",
  "Gitar",
  "Go",
  "Go Oyunu",
  "Golf",
  "Grafik Tasarım",
  "Guarani Dili",
  "Gölge Öğretmen",
  "Görme Engelliler",
  "Görsel Sanatlar",
  "Gücerat Dili",
  "Gürcüce",
  "Güreş",
  "Güzel Konuşma",
  "Güzel Sanatlar",
  "Gıda Müh.",
  "HTML",
  "Habeşçe",
  "Hafıza Geliştirme",
  "Halk Oyunları",
  "Halkla İlişkiler",
  "Harita Müh.",
  "Harmonika",
  "Harp",
  "Hayat Bilgisi",
  "Heykel",
  "Hintçe",
  "Hollandaca",
  "Hukuk",
  "Hırvatça",
  "Hızlı Okuma",
  "IELTS",
  "International Baccalaureate - Bilgisayar Bilimleri",
  "International Baccalaureate - Biyoloji",
  "International Baccalaureate - Dans",
  "International Baccalaureate - Drama",
  "International Baccalaureate - Edebiyat",
  "International Baccalaureate - Ekonomi",
  "International Baccalaureate - Felsefe",
  "International Baccalaureate - Filim",
  "International Baccalaureate - Fizik",
  "International Baccalaureate - Görsel Sanatlar",
  "International Baccalaureate - Kimya",
  "International Baccalaureate - Matematik",
  "International Baccalaureate - Müzik",
  "International Baccalaureate - Psikoloji",
  "International Baccalaureate - Tarih",
  "International Baccalaureate - Teknoloji",
  "International Baccalaureate - İşletme",
  "J2EE",
  "J2EE - Hibernate",
  "J2EE - Spring",
  "J2EE - Struts",
  "JANA",
  "JQuery",
  "JSP",
  "Japonca",
  "Java",
  "Java Dili",
  "Javascript",
  "Jeodezi Müh.",
  "Jeofizik Müh.",
  "Jeoloji Müh.",
  "Jimnastik",
  "Jive",
  "KDK Uzman Yardımcılığı",
  "KGK Bağımsız Denetçilik",
  "KPSS",
  "Kabak Kemane",
  "Kaligrafi",
  "Kamboçyaca",
  "Kamyon",
  "Kanun",
  "Kara Kalem",
  "Karikatür",
  "Kariyer Planlama",
  "Kart Oyunları",
  "Katalanca",
  "Kaval",
  "Kayak",
  "Kaymakamlık",
  "Kazakça",
  "Keman",
  "Kemençe",
  "KeyShot",
  "Keynote",
  "Kimya",
  "Kimya Müh.",
  "Klarnet",
  "Klavye",
  "Klingonca",
  "Kodlama",
  "Kompozisyon",
  "Kontrabas",
  "Korece",
  "Koreografi",
  "Korsika Dili",
  "Kuzey İskoç Dili",
  "Kürtçe",
  "KİT İç Denetçi",
  "Kırgızca",
  "LGS",
  "LINQ",
  "LS-Dyna",
  "LSAT",
  "Laosça",
  "Latince",
  "Lavta",
  "Lehçe",
  "Letonyaca",
  "Lingalaca",
  "Linux",
  "Litvanyaca",
  "Lumion",
  "MCAT",
  "MHUY",
  "MS .NET",
  "MS Access",
  "MS Excel",
  "MS FoxPro",
  "MS Outlook",
  "MS PowerPoint",
  "MS Project",
  "MS Visio",
  "MS Visual Basic",
  "MS Windows",
  "MS Word",
  "MSÜ",
  "MacOS",
  "Macarca",
  "Maden Müh.",
  "Makedonca",
  "Makina Müh.",
  "Makine Öğrenmesi",
  "Malayalam",
  "Malezya Dili",
  "Maltaca",
  "Mambo",
  "Mandolin",
  "Mantık",
  "Marakas",
  "Marathi",
  "Marc",
  "Masa Tenisi",
  "Matematik",
  "Matlab",
  "Mekatronik Müh.",
  "Melodika",
  "Mental Aritmetik",
  "Merenge",
  "Meteoroloji Müh.",
  "Mikrobiyoloji",
  "Mimarlık",
  "Mobil Uygulama Geliştirme",
  "Modelleme",
  "Modern Dans",
  "Moldovyaca",
  "Moleküler Biyoloji",
  "Motor Sporları",
  "Motosiklet",
  "Moğolca",
  "Muhasebe",
  "Multimedya",
  "MySQL",
  "Mühendislik Tamamlama",
  "Müzik",
  "Müzik Prodüksiyon",
  "Müzik Tarihi",
  "Müzik Teknolojileri",
  "Müzik Teorisi",
  "Müzik Yapımı",
  "Mızrap",
  "Mızıka",
  "NLP",
  "NX Unigraphics",
  "Nefesli Çalgılar",
  "Nepalce",
  "Netcad",
  "Network",
  "Ney",
  "Node.JS",
  "Norveçce",
  "Numeroloji",
  "Nükleer Müh.",
  "OET",
  "Oboe",
  "Okey",
  "Okuma Yazma Güçlüğü",
  "Okuma-Yazma",
  "Okçuluk",
  "Opera",
  "Optisyenlik",
  "Oracle",
  "Org",
  "Origami",
  "Orman Müh.",
  "Ortopedik Engelliler",
  "Oryantal",
  "Oryantiring",
  "Osmanlı Türkçesi",
  "Osmanlıca",
  "Otizim Spektrum Bozukluğu",
  "Otobüs",
  "Otomobil",
  "Otomotiv Müh.",
  "Oyun Abisi/Ablası",
  "Oyun Yazımı",
  "PHP",
  "PHP - Symfony",
  "PMP",
  "PMYO",
  "PPL",
  "PTE Academic",
  "PTE General",
  "PTE Young Learners",
  "PYBS",
  "Paraşüt",
  "Pascal",
  "Paso Doble",
  "Paten",
  "Patoloji",
  "Pazarlama",
  "Pencap Dili",
  "Perl",
  "Petrol ve Doğal Gaz Müh.",
  "Peyzaj",
  "Peştuca",
  "PhoneGap",
  "Photoshop",
  "Piano",
  "Pilates",
  "Poker",
  "Polonyaca",
  "Portekizce",
  "Prezentasyon",
  "Prezi",
  "Programlama",
  "Proje Hazırlama",
  "Proje Yönetimi",
  "Prolog",
  "Psikoloji",
  "Python",
  "Quickstep",
  "R",
  "React Native",
  "Reklamcılık",
  "Resim",
  "Rezüme Hazırlama",
  "Rhinoceros 3D",
  "Risk Yönetimi",
  "Robotik",
  "Roman Yazımı",
  "Romanşça",
  "Romence",
  "Ruby On Rails",
  "Rumba",
  "Rusça",
  "Rüzgar Sörfü",
  "SAP",
  "SAS",
  "SAT",
  "SEO",
  "SMMM",
  "SPK",
  "SPSS",
  "SQL",
  "STEP Eiken",
  "STS Diş Hekimliği",
  "STS Eczacılık",
  "STS Tıp Doktorluğu",
  "Saksofon",
  "Salsa",
  "Samba",
  "Sanat Tarihi",
  "Sap2000",
  "Satranç",
  "Satış",
  "Sayıştay Eleme",
  "Sayıştay Yazılı",
  "Saz",
  "Seramik",
  "Ses Mühendisliği",
  "Ses Üretimi",
  "Sesotho Dili",
  "Simulia",
  "Simulink",
  "Sinema",
  "Sistem ve Kontrol Müh.",
  "Siyaset",
  "SketchUp",
  "Skuba",
  "Slovakça",
  "Slovence",
  "Solfej",
  "SolidCAM",
  "SolidWorks",
  "Somalice",
  "Sosyal Bilgiler",
  "Sosyal Hizmetler",
  "Sosyoloji",
  "Sri Lankaca",
  "Sta4CAD",
  "Stenografi",
  "Stratejik Planlama",
  "Sundanizce",
  "Svahili",
  "Sörf",
  "Sırpça",
  "TCP/IP",
  "TEPS",
  "TIPDİL",
  "TMGD",
  "TODAİE",
  "TOEFL",
  "TOEIC",
  "TORFL",
  "TRACE",
  "TUS",
  "TYT",
  "Tacikce",
  "Takı Tasarımı",
  "Tambur",
  "Tamil",
  "Tango",
  "Tarih",
  "Tarım",
  "Tarım Müh.",
  "Tatarca",
  "Tavla",
  "Tay Dili",
  "Tef",
  "Tekla Xsteel",
  "Teknik Resim",
  "Teknoloji ve Tasarım",
  "Tekstil Müh.",
  "Telekomunikasyon Müh.",
  "Telli Çalgılar",
  "Telugu",
  "Temel Bilgisayar Bilgisi",
  "Tenis",
  "Ticaret",
  "Tiyatro",
  "Tongaca",
  "Trafik",
  "Trinity College - GESE",
  "Trinity College - ISE",
  "Trinity College - SEW",
  "Trombon",
  "Trompet",
  "Tuba",
  "Tulum",
  "Tumba",
  "Turizm",
  "Tuşlu Çalgılar",
  "Tvi Dili",
  "Türk Dili ve Edebiyatı",
  "Türk Edebiyatı",
  "Türk Müziği",
  "Türkmence",
  "Türkçe",
  "Tıbbi Sistemler Müh.",
  "Tıp",
  "Ud",
  "Ukraynaca",
  "Ukulele",
  "Uluslararası İlişkiler",
  "Unity",
  "Unix",
  "Urduca",
  "Uygulama Geliştirme",
  "Uygur Dili",
  "Uyum Güçlügü Olan Çocuklar",
  "Uzak Doğu Sporları",
  "Uzay Müh.",
  "Uçak Müh.",
  "VDK Müfettiş Yardımcılığı",
  "Vatandaşlık",
  "Vergi",
  "Veritabanları",
  "Vietnamca",
  "Viyola",
  "Voleybol",
  "Vurmalı Çalgılar",
  "Vücut geliştirme",
  "Waltz",
  "Web Programlama",
  "Web Tasarımı",
  "XCode",
  "Xamarin",
  "YDS",
  "YDUS",
  "YKS",
  "YLSY",
  "YMM",
  "YSK",
  "Yabancı Dil",
  "Yamaç Paraşütü",
  "Yan Flüt",
  "Yapay Sinir Ağları",
  "Yapay Zeka",
  "Yaratıcı Yazarlık",
  "Yazmayı Öğrenme",
  "Yazılım Müh.",
  "Yazılım Mühendisliği",
  "Yelkencilik",
  "Yetenek Sınavları - Endüstri Ürünleri Tasarımı",
  "Yetenek Sınavları - Fotoğraf",
  "Yetenek Sınavları - Grafik Tasarım",
  "Yetenek Sınavları - Heykel",
  "Yetenek Sınavları - Müzik",
  "Yetenek Sınavları - Resim",
  "Yetenek Sınavları - Sahne Dekorları ve Kostümü",
  "Yetenek Sınavları - Seramik ve Cam Tasarımı",
  "Yetenek Sınavları - Tekstil ve Moda Tasarımı",
  "Yetenek Sınavları - Tiyatro",
  "Yetenek Sınavları - İç Mimarlık",
  "Yidce",
  "Yoga",
  "Yoruba Dili",
  "Yunanca",
  "YÖKDİL",
  "YÖS",
  "Yöneticilik",
  "Yüzme",
  "Zaman Yönetimi",
  "Zihinsel Engelliler",
  "Zil",
  "Zulu Dili",
  "Zumba",
  "Zurna",
  "iOS",
  "Çekoslavakça",
  "Çello",
  "Çeviri",
  "Çince",
  "Çizim",
  "Örgü",
  "Öykü Yazımı",
  "Özbekçe",
  "Özgül Öğrenme Problemi",
  "ÜDS",
  "ÜGYS",
  "Üretim Müh.",
  "Üstün Yetenekli Çocuklar",
  "İSG",
  "İbranice",
  "İcra Müdür Yardımcılığı",
  "İktisat",
  "İletişim",
  "İletişim ve Sunum",
  "İllüstrasyon",
  "İllüzyon",
  "İngiliz Edebiyatı",
  "İngilizce",
  "İnka Dili",
  "İnternet",
  "İnşaat Müh.",
  "İrlandaca",
  "İspanyolca",
  "İstatistik",
  "İsveçce",
  "İtalyan Edebiyatı",
  "İtalyanca",
  "İzlandaca",
  "İç Denetçi",
  "İç Mimarlık",
  "İç Tasarım",
  "İş Kurma",
  "İş Makinaları",
  "İş Planlama",
  "İş Sürekliliği Yönetimi",
  "İş İdaresi",
  "İşitme Engelliler",
  "İşletim Sistemleri",
  "İşletme",
  "İşletme Müh.",
  "Şan",
  "Şarkı Aranje",
  "Şarkı Besteleme",
  "Şarkı Ka",
  "Şarkı Kayıt",
  "Şehir ve Bölge Planlama"
];
